package tools.colors;

@javax.annotation.Generated(value = {"dashboard.Main"}, date = "Tuesday, June 21, 2016 10:45:55 AM UTC")
public final class NamedColorConstants
{
	private NamedColorConstants(){}
	/**A color with an ARGB value of 0xfff0f8ff<div style="border:1px solid black;width:40px;height:20px;background-color:#f0f8ff;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor ALICEBLUE= new NamedColor("ALICEBLUE", new java.awt.Color(0xfff0f8ff, true));
	/**A color with an ARGB value of 0xfff0f8ff<div style="border:1px solid black;width:40px;height:20px;background-color:#f0f8ff;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor aliceblue= new NamedColor("aliceblue", new java.awt.Color(0xfff0f8ff, true));
	/**A color with an ARGB value of 0xfffaebd7<div style="border:1px solid black;width:40px;height:20px;background-color:#faebd7;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor ANTIQUEWHITE= new NamedColor("ANTIQUEWHITE", new java.awt.Color(0xfffaebd7, true));
	/**A color with an ARGB value of 0xfffaebd7<div style="border:1px solid black;width:40px;height:20px;background-color:#faebd7;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor antiquewhite= new NamedColor("antiquewhite", new java.awt.Color(0xfffaebd7, true));
	/**A color with an ARGB value of 0xff00ffff<div style="border:1px solid black;width:40px;height:20px;background-color:#00ffff;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor AQUA= new NamedColor("AQUA", new java.awt.Color(0xff00ffff, true));
	/**A color with an ARGB value of 0xff00ffff<div style="border:1px solid black;width:40px;height:20px;background-color:#00ffff;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor aqua= new NamedColor("aqua", new java.awt.Color(0xff00ffff, true));
	/**A color with an ARGB value of 0xff7fffd4<div style="border:1px solid black;width:40px;height:20px;background-color:#7fffd4;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor AQUAMARINE= new NamedColor("AQUAMARINE", new java.awt.Color(0xff7fffd4, true));
	/**A color with an ARGB value of 0xff7fffd4<div style="border:1px solid black;width:40px;height:20px;background-color:#7fffd4;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor aquamarine= new NamedColor("aquamarine", new java.awt.Color(0xff7fffd4, true));
	/**A color with an ARGB value of 0xfff0ffff<div style="border:1px solid black;width:40px;height:20px;background-color:#f0ffff;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor AZURE= new NamedColor("AZURE", new java.awt.Color(0xfff0ffff, true));
	/**A color with an ARGB value of 0xfff0ffff<div style="border:1px solid black;width:40px;height:20px;background-color:#f0ffff;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor azure= new NamedColor("azure", new java.awt.Color(0xfff0ffff, true));
	/**A color with an ARGB value of 0xfff5f5dc<div style="border:1px solid black;width:40px;height:20px;background-color:#f5f5dc;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor BEIGE= new NamedColor("BEIGE", new java.awt.Color(0xfff5f5dc, true));
	/**A color with an ARGB value of 0xfff5f5dc<div style="border:1px solid black;width:40px;height:20px;background-color:#f5f5dc;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor beige= new NamedColor("beige", new java.awt.Color(0xfff5f5dc, true));
	/**A color with an ARGB value of 0xffffe4c4<div style="border:1px solid black;width:40px;height:20px;background-color:#ffe4c4;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor BISQUE= new NamedColor("BISQUE", new java.awt.Color(0xffffe4c4, true));
	/**A color with an ARGB value of 0xffffe4c4<div style="border:1px solid black;width:40px;height:20px;background-color:#ffe4c4;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor bisque= new NamedColor("bisque", new java.awt.Color(0xffffe4c4, true));
	/**A color with an ARGB value of 0xff000000<div style="border:1px solid black;width:40px;height:20px;background-color:#000000;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor BLACK= new NamedColor("BLACK", new java.awt.Color(0xff000000, true));
	/**A color with an ARGB value of 0xff000000<div style="border:1px solid black;width:40px;height:20px;background-color:#000000;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor black= new NamedColor("black", new java.awt.Color(0xff000000, true));
	/**A color with an ARGB value of 0xffffebcd<div style="border:1px solid black;width:40px;height:20px;background-color:#ffebcd;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor BLANCHEDALMOND= new NamedColor("BLANCHEDALMOND", new java.awt.Color(0xffffebcd, true));
	/**A color with an ARGB value of 0xffffebcd<div style="border:1px solid black;width:40px;height:20px;background-color:#ffebcd;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor blanchedalmond= new NamedColor("blanchedalmond", new java.awt.Color(0xffffebcd, true));
	/**A color with an ARGB value of 0xff0000ff<div style="border:1px solid black;width:40px;height:20px;background-color:#0000ff;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor BLUE= new NamedColor("BLUE", new java.awt.Color(0xff0000ff, true));
	/**A color with an ARGB value of 0xff0000ff<div style="border:1px solid black;width:40px;height:20px;background-color:#0000ff;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor blue= new NamedColor("blue", new java.awt.Color(0xff0000ff, true));
	/**A color with an ARGB value of 0xff8a2be2<div style="border:1px solid black;width:40px;height:20px;background-color:#8a2be2;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor BLUEVIOLET= new NamedColor("BLUEVIOLET", new java.awt.Color(0xff8a2be2, true));
	/**A color with an ARGB value of 0xff8a2be2<div style="border:1px solid black;width:40px;height:20px;background-color:#8a2be2;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor blueviolet= new NamedColor("blueviolet", new java.awt.Color(0xff8a2be2, true));
	/**A color with an ARGB value of 0xffa52a2a<div style="border:1px solid black;width:40px;height:20px;background-color:#a52a2a;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor BROWN= new NamedColor("BROWN", new java.awt.Color(0xffa52a2a, true));
	/**A color with an ARGB value of 0xffa52a2a<div style="border:1px solid black;width:40px;height:20px;background-color:#a52a2a;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor brown= new NamedColor("brown", new java.awt.Color(0xffa52a2a, true));
	/**A color with an ARGB value of 0xffdeb887<div style="border:1px solid black;width:40px;height:20px;background-color:#deb887;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor BURLYWOOD= new NamedColor("BURLYWOOD", new java.awt.Color(0xffdeb887, true));
	/**A color with an ARGB value of 0xffdeb887<div style="border:1px solid black;width:40px;height:20px;background-color:#deb887;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor burlywood= new NamedColor("burlywood", new java.awt.Color(0xffdeb887, true));
	/**A color with an ARGB value of 0xff5f9ea0<div style="border:1px solid black;width:40px;height:20px;background-color:#5f9ea0;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor CADETBLUE= new NamedColor("CADETBLUE", new java.awt.Color(0xff5f9ea0, true));
	/**A color with an ARGB value of 0xff5f9ea0<div style="border:1px solid black;width:40px;height:20px;background-color:#5f9ea0;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor cadetblue= new NamedColor("cadetblue", new java.awt.Color(0xff5f9ea0, true));
	/**A color with an ARGB value of 0xff7fff00<div style="border:1px solid black;width:40px;height:20px;background-color:#7fff00;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor CHARTREUSE= new NamedColor("CHARTREUSE", new java.awt.Color(0xff7fff00, true));
	/**A color with an ARGB value of 0xff7fff00<div style="border:1px solid black;width:40px;height:20px;background-color:#7fff00;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor chartreuse= new NamedColor("chartreuse", new java.awt.Color(0xff7fff00, true));
	/**A color with an ARGB value of 0xffd2691e<div style="border:1px solid black;width:40px;height:20px;background-color:#d2691e;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor CHOCOLATE= new NamedColor("CHOCOLATE", new java.awt.Color(0xffd2691e, true));
	/**A color with an ARGB value of 0xffd2691e<div style="border:1px solid black;width:40px;height:20px;background-color:#d2691e;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor chocolate= new NamedColor("chocolate", new java.awt.Color(0xffd2691e, true));
	/**A color with an ARGB value of 0xffff7f50<div style="border:1px solid black;width:40px;height:20px;background-color:#ff7f50;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor CORAL= new NamedColor("CORAL", new java.awt.Color(0xffff7f50, true));
	/**A color with an ARGB value of 0xffff7f50<div style="border:1px solid black;width:40px;height:20px;background-color:#ff7f50;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor coral= new NamedColor("coral", new java.awt.Color(0xffff7f50, true));
	/**A color with an ARGB value of 0xff6495ed<div style="border:1px solid black;width:40px;height:20px;background-color:#6495ed;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor CORNFLOWERBLUE= new NamedColor("CORNFLOWERBLUE", new java.awt.Color(0xff6495ed, true));
	/**A color with an ARGB value of 0xff6495ed<div style="border:1px solid black;width:40px;height:20px;background-color:#6495ed;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor cornflowerblue= new NamedColor("cornflowerblue", new java.awt.Color(0xff6495ed, true));
	/**A color with an ARGB value of 0xfffff8dc<div style="border:1px solid black;width:40px;height:20px;background-color:#fff8dc;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor CORNSILK= new NamedColor("CORNSILK", new java.awt.Color(0xfffff8dc, true));
	/**A color with an ARGB value of 0xfffff8dc<div style="border:1px solid black;width:40px;height:20px;background-color:#fff8dc;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor cornsilk= new NamedColor("cornsilk", new java.awt.Color(0xfffff8dc, true));
	/**A color with an ARGB value of 0xffdc143c<div style="border:1px solid black;width:40px;height:20px;background-color:#dc143c;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor CRIMSON= new NamedColor("CRIMSON", new java.awt.Color(0xffdc143c, true));
	/**A color with an ARGB value of 0xffdc143c<div style="border:1px solid black;width:40px;height:20px;background-color:#dc143c;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor crimson= new NamedColor("crimson", new java.awt.Color(0xffdc143c, true));
	/**A color with an ARGB value of 0xff00ffff<div style="border:1px solid black;width:40px;height:20px;background-color:#00ffff;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor CYAN= new NamedColor("CYAN", new java.awt.Color(0xff00ffff, true));
	/**A color with an ARGB value of 0xff00ffff<div style="border:1px solid black;width:40px;height:20px;background-color:#00ffff;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor cyan= new NamedColor("cyan", new java.awt.Color(0xff00ffff, true));
	/**A color with an ARGB value of 0xff404040<div style="border:1px solid black;width:40px;height:20px;background-color:#404040;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DARK_GRAY= new NamedColor("DARK_GRAY", new java.awt.Color(0xff404040, true));
	/**A color with an ARGB value of 0xff404040<div style="border:1px solid black;width:40px;height:20px;background-color:#404040;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor dark_gray= new NamedColor("dark_gray", new java.awt.Color(0xff404040, true));
	/**A color with an ARGB value of 0xff00008b<div style="border:1px solid black;width:40px;height:20px;background-color:#00008b;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DARKBLUE= new NamedColor("DARKBLUE", new java.awt.Color(0xff00008b, true));
	/**A color with an ARGB value of 0xff00008b<div style="border:1px solid black;width:40px;height:20px;background-color:#00008b;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor darkblue= new NamedColor("darkblue", new java.awt.Color(0xff00008b, true));
	/**A color with an ARGB value of 0xff008b8b<div style="border:1px solid black;width:40px;height:20px;background-color:#008b8b;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DARKCYAN= new NamedColor("DARKCYAN", new java.awt.Color(0xff008b8b, true));
	/**A color with an ARGB value of 0xff008b8b<div style="border:1px solid black;width:40px;height:20px;background-color:#008b8b;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor darkcyan= new NamedColor("darkcyan", new java.awt.Color(0xff008b8b, true));
	/**A color with an ARGB value of 0xffb8860b<div style="border:1px solid black;width:40px;height:20px;background-color:#b8860b;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DARKGOLDENROD= new NamedColor("DARKGOLDENROD", new java.awt.Color(0xffb8860b, true));
	/**A color with an ARGB value of 0xffb8860b<div style="border:1px solid black;width:40px;height:20px;background-color:#b8860b;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor darkgoldenrod= new NamedColor("darkgoldenrod", new java.awt.Color(0xffb8860b, true));
	/**A color with an ARGB value of 0xff404040<div style="border:1px solid black;width:40px;height:20px;background-color:#404040;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DARKGRAY= new NamedColor("DARKGRAY", new java.awt.Color(0xff404040, true));
	/**A color with an ARGB value of 0xff404040<div style="border:1px solid black;width:40px;height:20px;background-color:#404040;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor darkgray= new NamedColor("darkgray", new java.awt.Color(0xff404040, true));
	/**A color with an ARGB value of 0xffa9a9a9<div style="border:1px solid black;width:40px;height:20px;background-color:#a9a9a9;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DARKGRAY2= new NamedColor("DARKGRAY2", new java.awt.Color(0xffa9a9a9, true));
	/**A color with an ARGB value of 0xffa9a9a9<div style="border:1px solid black;width:40px;height:20px;background-color:#a9a9a9;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor darkgray2= new NamedColor("darkgray2", new java.awt.Color(0xffa9a9a9, true));
	/**A color with an ARGB value of 0xff006400<div style="border:1px solid black;width:40px;height:20px;background-color:#006400;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DARKGREEN= new NamedColor("DARKGREEN", new java.awt.Color(0xff006400, true));
	/**A color with an ARGB value of 0xff006400<div style="border:1px solid black;width:40px;height:20px;background-color:#006400;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor darkgreen= new NamedColor("darkgreen", new java.awt.Color(0xff006400, true));
	/**A color with an ARGB value of 0xffa9a9a9<div style="border:1px solid black;width:40px;height:20px;background-color:#a9a9a9;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DARKGREY= new NamedColor("DARKGREY", new java.awt.Color(0xffa9a9a9, true));
	/**A color with an ARGB value of 0xffa9a9a9<div style="border:1px solid black;width:40px;height:20px;background-color:#a9a9a9;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor darkgrey= new NamedColor("darkgrey", new java.awt.Color(0xffa9a9a9, true));
	/**A color with an ARGB value of 0xffbdb76b<div style="border:1px solid black;width:40px;height:20px;background-color:#bdb76b;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DARKKHAKI= new NamedColor("DARKKHAKI", new java.awt.Color(0xffbdb76b, true));
	/**A color with an ARGB value of 0xffbdb76b<div style="border:1px solid black;width:40px;height:20px;background-color:#bdb76b;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor darkkhaki= new NamedColor("darkkhaki", new java.awt.Color(0xffbdb76b, true));
	/**A color with an ARGB value of 0xff8b008b<div style="border:1px solid black;width:40px;height:20px;background-color:#8b008b;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DARKMAGENTA= new NamedColor("DARKMAGENTA", new java.awt.Color(0xff8b008b, true));
	/**A color with an ARGB value of 0xff8b008b<div style="border:1px solid black;width:40px;height:20px;background-color:#8b008b;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor darkmagenta= new NamedColor("darkmagenta", new java.awt.Color(0xff8b008b, true));
	/**A color with an ARGB value of 0xff556b2f<div style="border:1px solid black;width:40px;height:20px;background-color:#556b2f;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DARKOLIVEGREEN= new NamedColor("DARKOLIVEGREEN", new java.awt.Color(0xff556b2f, true));
	/**A color with an ARGB value of 0xff556b2f<div style="border:1px solid black;width:40px;height:20px;background-color:#556b2f;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor darkolivegreen= new NamedColor("darkolivegreen", new java.awt.Color(0xff556b2f, true));
	/**A color with an ARGB value of 0xffff8c00<div style="border:1px solid black;width:40px;height:20px;background-color:#ff8c00;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DARKORANGE= new NamedColor("DARKORANGE", new java.awt.Color(0xffff8c00, true));
	/**A color with an ARGB value of 0xffff8c00<div style="border:1px solid black;width:40px;height:20px;background-color:#ff8c00;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor darkorange= new NamedColor("darkorange", new java.awt.Color(0xffff8c00, true));
	/**A color with an ARGB value of 0xff9932cc<div style="border:1px solid black;width:40px;height:20px;background-color:#9932cc;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DARKORCHID= new NamedColor("DARKORCHID", new java.awt.Color(0xff9932cc, true));
	/**A color with an ARGB value of 0xff9932cc<div style="border:1px solid black;width:40px;height:20px;background-color:#9932cc;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor darkorchid= new NamedColor("darkorchid", new java.awt.Color(0xff9932cc, true));
	/**A color with an ARGB value of 0xff8b0000<div style="border:1px solid black;width:40px;height:20px;background-color:#8b0000;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DARKRED= new NamedColor("DARKRED", new java.awt.Color(0xff8b0000, true));
	/**A color with an ARGB value of 0xff8b0000<div style="border:1px solid black;width:40px;height:20px;background-color:#8b0000;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor darkred= new NamedColor("darkred", new java.awt.Color(0xff8b0000, true));
	/**A color with an ARGB value of 0xffe9967a<div style="border:1px solid black;width:40px;height:20px;background-color:#e9967a;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DARKSALMON= new NamedColor("DARKSALMON", new java.awt.Color(0xffe9967a, true));
	/**A color with an ARGB value of 0xffe9967a<div style="border:1px solid black;width:40px;height:20px;background-color:#e9967a;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor darksalmon= new NamedColor("darksalmon", new java.awt.Color(0xffe9967a, true));
	/**A color with an ARGB value of 0xff8fbc8f<div style="border:1px solid black;width:40px;height:20px;background-color:#8fbc8f;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DARKSEAGREEN= new NamedColor("DARKSEAGREEN", new java.awt.Color(0xff8fbc8f, true));
	/**A color with an ARGB value of 0xff8fbc8f<div style="border:1px solid black;width:40px;height:20px;background-color:#8fbc8f;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor darkseagreen= new NamedColor("darkseagreen", new java.awt.Color(0xff8fbc8f, true));
	/**A color with an ARGB value of 0xff483d8b<div style="border:1px solid black;width:40px;height:20px;background-color:#483d8b;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DARKSLATEBLUE= new NamedColor("DARKSLATEBLUE", new java.awt.Color(0xff483d8b, true));
	/**A color with an ARGB value of 0xff483d8b<div style="border:1px solid black;width:40px;height:20px;background-color:#483d8b;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor darkslateblue= new NamedColor("darkslateblue", new java.awt.Color(0xff483d8b, true));
	/**A color with an ARGB value of 0xff2f4f4f<div style="border:1px solid black;width:40px;height:20px;background-color:#2f4f4f;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DARKSLATEGRAY= new NamedColor("DARKSLATEGRAY", new java.awt.Color(0xff2f4f4f, true));
	/**A color with an ARGB value of 0xff2f4f4f<div style="border:1px solid black;width:40px;height:20px;background-color:#2f4f4f;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor darkslategray= new NamedColor("darkslategray", new java.awt.Color(0xff2f4f4f, true));
	/**A color with an ARGB value of 0xff2f4f4f<div style="border:1px solid black;width:40px;height:20px;background-color:#2f4f4f;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DARKSLATEGREY= new NamedColor("DARKSLATEGREY", new java.awt.Color(0xff2f4f4f, true));
	/**A color with an ARGB value of 0xff2f4f4f<div style="border:1px solid black;width:40px;height:20px;background-color:#2f4f4f;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor darkslategrey= new NamedColor("darkslategrey", new java.awt.Color(0xff2f4f4f, true));
	/**A color with an ARGB value of 0xff00ced1<div style="border:1px solid black;width:40px;height:20px;background-color:#00ced1;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DARKTURQUOISE= new NamedColor("DARKTURQUOISE", new java.awt.Color(0xff00ced1, true));
	/**A color with an ARGB value of 0xff00ced1<div style="border:1px solid black;width:40px;height:20px;background-color:#00ced1;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor darkturquoise= new NamedColor("darkturquoise", new java.awt.Color(0xff00ced1, true));
	/**A color with an ARGB value of 0xff9400d3<div style="border:1px solid black;width:40px;height:20px;background-color:#9400d3;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DARKVIOLET= new NamedColor("DARKVIOLET", new java.awt.Color(0xff9400d3, true));
	/**A color with an ARGB value of 0xff9400d3<div style="border:1px solid black;width:40px;height:20px;background-color:#9400d3;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor darkviolet= new NamedColor("darkviolet", new java.awt.Color(0xff9400d3, true));
	/**A color with an ARGB value of 0xffff1493<div style="border:1px solid black;width:40px;height:20px;background-color:#ff1493;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DEEPPINK= new NamedColor("DEEPPINK", new java.awt.Color(0xffff1493, true));
	/**A color with an ARGB value of 0xffff1493<div style="border:1px solid black;width:40px;height:20px;background-color:#ff1493;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor deeppink= new NamedColor("deeppink", new java.awt.Color(0xffff1493, true));
	/**A color with an ARGB value of 0xff00bfff<div style="border:1px solid black;width:40px;height:20px;background-color:#00bfff;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DEEPSKYBLUE= new NamedColor("DEEPSKYBLUE", new java.awt.Color(0xff00bfff, true));
	/**A color with an ARGB value of 0xff00bfff<div style="border:1px solid black;width:40px;height:20px;background-color:#00bfff;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor deepskyblue= new NamedColor("deepskyblue", new java.awt.Color(0xff00bfff, true));
	/**A color with an ARGB value of 0xff696969<div style="border:1px solid black;width:40px;height:20px;background-color:#696969;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DIMGRAY= new NamedColor("DIMGRAY", new java.awt.Color(0xff696969, true));
	/**A color with an ARGB value of 0xff696969<div style="border:1px solid black;width:40px;height:20px;background-color:#696969;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor dimgray= new NamedColor("dimgray", new java.awt.Color(0xff696969, true));
	/**A color with an ARGB value of 0xff696969<div style="border:1px solid black;width:40px;height:20px;background-color:#696969;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DIMGREY= new NamedColor("DIMGREY", new java.awt.Color(0xff696969, true));
	/**A color with an ARGB value of 0xff696969<div style="border:1px solid black;width:40px;height:20px;background-color:#696969;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor dimgrey= new NamedColor("dimgrey", new java.awt.Color(0xff696969, true));
	/**A color with an ARGB value of 0xff1e90ff<div style="border:1px solid black;width:40px;height:20px;background-color:#1e90ff;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DODGERBLUE= new NamedColor("DODGERBLUE", new java.awt.Color(0xff1e90ff, true));
	/**A color with an ARGB value of 0xff1e90ff<div style="border:1px solid black;width:40px;height:20px;background-color:#1e90ff;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor dodgerblue= new NamedColor("dodgerblue", new java.awt.Color(0xff1e90ff, true));
	/**A color with an ARGB value of 0xffb22222<div style="border:1px solid black;width:40px;height:20px;background-color:#b22222;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor FIREBRICK= new NamedColor("FIREBRICK", new java.awt.Color(0xffb22222, true));
	/**A color with an ARGB value of 0xffb22222<div style="border:1px solid black;width:40px;height:20px;background-color:#b22222;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor firebrick= new NamedColor("firebrick", new java.awt.Color(0xffb22222, true));
	/**A color with an ARGB value of 0xfffffaf0<div style="border:1px solid black;width:40px;height:20px;background-color:#fffaf0;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor FLORALWHITE= new NamedColor("FLORALWHITE", new java.awt.Color(0xfffffaf0, true));
	/**A color with an ARGB value of 0xfffffaf0<div style="border:1px solid black;width:40px;height:20px;background-color:#fffaf0;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor floralwhite= new NamedColor("floralwhite", new java.awt.Color(0xfffffaf0, true));
	/**A color with an ARGB value of 0xff228b22<div style="border:1px solid black;width:40px;height:20px;background-color:#228b22;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor FORESTGREEN= new NamedColor("FORESTGREEN", new java.awt.Color(0xff228b22, true));
	/**A color with an ARGB value of 0xff228b22<div style="border:1px solid black;width:40px;height:20px;background-color:#228b22;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor forestgreen= new NamedColor("forestgreen", new java.awt.Color(0xff228b22, true));
	/**A color with an ARGB value of 0xffff00ff<div style="border:1px solid black;width:40px;height:20px;background-color:#ff00ff;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor FUCHSIA= new NamedColor("FUCHSIA", new java.awt.Color(0xffff00ff, true));
	/**A color with an ARGB value of 0xffff00ff<div style="border:1px solid black;width:40px;height:20px;background-color:#ff00ff;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor fuchsia= new NamedColor("fuchsia", new java.awt.Color(0xffff00ff, true));
	/**A color with an ARGB value of 0xffdcdcdc<div style="border:1px solid black;width:40px;height:20px;background-color:#dcdcdc;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor GAINSBORO= new NamedColor("GAINSBORO", new java.awt.Color(0xffdcdcdc, true));
	/**A color with an ARGB value of 0xffdcdcdc<div style="border:1px solid black;width:40px;height:20px;background-color:#dcdcdc;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor gainsboro= new NamedColor("gainsboro", new java.awt.Color(0xffdcdcdc, true));
	/**A color with an ARGB value of 0xfff8f8ff<div style="border:1px solid black;width:40px;height:20px;background-color:#f8f8ff;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor GHOSTWHITE= new NamedColor("GHOSTWHITE", new java.awt.Color(0xfff8f8ff, true));
	/**A color with an ARGB value of 0xfff8f8ff<div style="border:1px solid black;width:40px;height:20px;background-color:#f8f8ff;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor ghostwhite= new NamedColor("ghostwhite", new java.awt.Color(0xfff8f8ff, true));
	/**A color with an ARGB value of 0xffffd700<div style="border:1px solid black;width:40px;height:20px;background-color:#ffd700;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor GOLD= new NamedColor("GOLD", new java.awt.Color(0xffffd700, true));
	/**A color with an ARGB value of 0xffffd700<div style="border:1px solid black;width:40px;height:20px;background-color:#ffd700;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor gold= new NamedColor("gold", new java.awt.Color(0xffffd700, true));
	/**A color with an ARGB value of 0xffdaa520<div style="border:1px solid black;width:40px;height:20px;background-color:#daa520;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor GOLDENROD= new NamedColor("GOLDENROD", new java.awt.Color(0xffdaa520, true));
	/**A color with an ARGB value of 0xffdaa520<div style="border:1px solid black;width:40px;height:20px;background-color:#daa520;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor goldenrod= new NamedColor("goldenrod", new java.awt.Color(0xffdaa520, true));
	/**A color with an ARGB value of 0xff808080<div style="border:1px solid black;width:40px;height:20px;background-color:#808080;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor GRAY= new NamedColor("GRAY", new java.awt.Color(0xff808080, true));
	/**A color with an ARGB value of 0xff808080<div style="border:1px solid black;width:40px;height:20px;background-color:#808080;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor gray= new NamedColor("gray", new java.awt.Color(0xff808080, true));
	/**A color with an ARGB value of 0xff008000<div style="border:1px solid black;width:40px;height:20px;background-color:#008000;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor GREEN= new NamedColor("GREEN", new java.awt.Color(0xff008000, true));
	/**A color with an ARGB value of 0xff008000<div style="border:1px solid black;width:40px;height:20px;background-color:#008000;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor green= new NamedColor("green", new java.awt.Color(0xff008000, true));
	/**A color with an ARGB value of 0xff00ff00<div style="border:1px solid black;width:40px;height:20px;background-color:#00ff00;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor GREEN2= new NamedColor("GREEN2", new java.awt.Color(0xff00ff00, true));
	/**A color with an ARGB value of 0xff00ff00<div style="border:1px solid black;width:40px;height:20px;background-color:#00ff00;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor green2= new NamedColor("green2", new java.awt.Color(0xff00ff00, true));
	/**A color with an ARGB value of 0xffadff2f<div style="border:1px solid black;width:40px;height:20px;background-color:#adff2f;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor GREENYELLOW= new NamedColor("GREENYELLOW", new java.awt.Color(0xffadff2f, true));
	/**A color with an ARGB value of 0xffadff2f<div style="border:1px solid black;width:40px;height:20px;background-color:#adff2f;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor greenyellow= new NamedColor("greenyellow", new java.awt.Color(0xffadff2f, true));
	/**A color with an ARGB value of 0xff808080<div style="border:1px solid black;width:40px;height:20px;background-color:#808080;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor GREY= new NamedColor("GREY", new java.awt.Color(0xff808080, true));
	/**A color with an ARGB value of 0xff808080<div style="border:1px solid black;width:40px;height:20px;background-color:#808080;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor grey= new NamedColor("grey", new java.awt.Color(0xff808080, true));
	/**A color with an ARGB value of 0xfff0fff0<div style="border:1px solid black;width:40px;height:20px;background-color:#f0fff0;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor HONEYDEW= new NamedColor("HONEYDEW", new java.awt.Color(0xfff0fff0, true));
	/**A color with an ARGB value of 0xfff0fff0<div style="border:1px solid black;width:40px;height:20px;background-color:#f0fff0;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor honeydew= new NamedColor("honeydew", new java.awt.Color(0xfff0fff0, true));
	/**A color with an ARGB value of 0xffff69b4<div style="border:1px solid black;width:40px;height:20px;background-color:#ff69b4;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor HOTPINK= new NamedColor("HOTPINK", new java.awt.Color(0xffff69b4, true));
	/**A color with an ARGB value of 0xffff69b4<div style="border:1px solid black;width:40px;height:20px;background-color:#ff69b4;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor hotpink= new NamedColor("hotpink", new java.awt.Color(0xffff69b4, true));
	/**A color with an ARGB value of 0xffcd5c5c<div style="border:1px solid black;width:40px;height:20px;background-color:#cd5c5c;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor INDIANRED= new NamedColor("INDIANRED", new java.awt.Color(0xffcd5c5c, true));
	/**A color with an ARGB value of 0xffcd5c5c<div style="border:1px solid black;width:40px;height:20px;background-color:#cd5c5c;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor indianred= new NamedColor("indianred", new java.awt.Color(0xffcd5c5c, true));
	/**A color with an ARGB value of 0xff4b0082<div style="border:1px solid black;width:40px;height:20px;background-color:#4b0082;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor INDIGO= new NamedColor("INDIGO", new java.awt.Color(0xff4b0082, true));
	/**A color with an ARGB value of 0xff4b0082<div style="border:1px solid black;width:40px;height:20px;background-color:#4b0082;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor indigo= new NamedColor("indigo", new java.awt.Color(0xff4b0082, true));
	/**A color with an ARGB value of 0xfffffff0<div style="border:1px solid black;width:40px;height:20px;background-color:#fffff0;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor IVORY= new NamedColor("IVORY", new java.awt.Color(0xfffffff0, true));
	/**A color with an ARGB value of 0xfffffff0<div style="border:1px solid black;width:40px;height:20px;background-color:#fffff0;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor ivory= new NamedColor("ivory", new java.awt.Color(0xfffffff0, true));
	/**A color with an ARGB value of 0xfff0e68c<div style="border:1px solid black;width:40px;height:20px;background-color:#f0e68c;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor KHAKI= new NamedColor("KHAKI", new java.awt.Color(0xfff0e68c, true));
	/**A color with an ARGB value of 0xfff0e68c<div style="border:1px solid black;width:40px;height:20px;background-color:#f0e68c;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor khaki= new NamedColor("khaki", new java.awt.Color(0xfff0e68c, true));
	/**A color with an ARGB value of 0xffe6e6fa<div style="border:1px solid black;width:40px;height:20px;background-color:#e6e6fa;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LAVENDER= new NamedColor("LAVENDER", new java.awt.Color(0xffe6e6fa, true));
	/**A color with an ARGB value of 0xffe6e6fa<div style="border:1px solid black;width:40px;height:20px;background-color:#e6e6fa;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor lavender= new NamedColor("lavender", new java.awt.Color(0xffe6e6fa, true));
	/**A color with an ARGB value of 0xfffff0f5<div style="border:1px solid black;width:40px;height:20px;background-color:#fff0f5;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LAVENDERBLUSH= new NamedColor("LAVENDERBLUSH", new java.awt.Color(0xfffff0f5, true));
	/**A color with an ARGB value of 0xfffff0f5<div style="border:1px solid black;width:40px;height:20px;background-color:#fff0f5;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor lavenderblush= new NamedColor("lavenderblush", new java.awt.Color(0xfffff0f5, true));
	/**A color with an ARGB value of 0xff7cfc00<div style="border:1px solid black;width:40px;height:20px;background-color:#7cfc00;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LAWNGREEN= new NamedColor("LAWNGREEN", new java.awt.Color(0xff7cfc00, true));
	/**A color with an ARGB value of 0xff7cfc00<div style="border:1px solid black;width:40px;height:20px;background-color:#7cfc00;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor lawngreen= new NamedColor("lawngreen", new java.awt.Color(0xff7cfc00, true));
	/**A color with an ARGB value of 0xfffffacd<div style="border:1px solid black;width:40px;height:20px;background-color:#fffacd;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LEMONCHIFFON= new NamedColor("LEMONCHIFFON", new java.awt.Color(0xfffffacd, true));
	/**A color with an ARGB value of 0xfffffacd<div style="border:1px solid black;width:40px;height:20px;background-color:#fffacd;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor lemonchiffon= new NamedColor("lemonchiffon", new java.awt.Color(0xfffffacd, true));
	/**A color with an ARGB value of 0xffc0c0c0<div style="border:1px solid black;width:40px;height:20px;background-color:#c0c0c0;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LIGHT_GRAY= new NamedColor("LIGHT_GRAY", new java.awt.Color(0xffc0c0c0, true));
	/**A color with an ARGB value of 0xffc0c0c0<div style="border:1px solid black;width:40px;height:20px;background-color:#c0c0c0;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor light_gray= new NamedColor("light_gray", new java.awt.Color(0xffc0c0c0, true));
	/**A color with an ARGB value of 0xffadd8e6<div style="border:1px solid black;width:40px;height:20px;background-color:#add8e6;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LIGHTBLUE= new NamedColor("LIGHTBLUE", new java.awt.Color(0xffadd8e6, true));
	/**A color with an ARGB value of 0xffadd8e6<div style="border:1px solid black;width:40px;height:20px;background-color:#add8e6;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor lightblue= new NamedColor("lightblue", new java.awt.Color(0xffadd8e6, true));
	/**A color with an ARGB value of 0xfff08080<div style="border:1px solid black;width:40px;height:20px;background-color:#f08080;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LIGHTCORAL= new NamedColor("LIGHTCORAL", new java.awt.Color(0xfff08080, true));
	/**A color with an ARGB value of 0xfff08080<div style="border:1px solid black;width:40px;height:20px;background-color:#f08080;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor lightcoral= new NamedColor("lightcoral", new java.awt.Color(0xfff08080, true));
	/**A color with an ARGB value of 0xffe0ffff<div style="border:1px solid black;width:40px;height:20px;background-color:#e0ffff;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LIGHTCYAN= new NamedColor("LIGHTCYAN", new java.awt.Color(0xffe0ffff, true));
	/**A color with an ARGB value of 0xffe0ffff<div style="border:1px solid black;width:40px;height:20px;background-color:#e0ffff;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor lightcyan= new NamedColor("lightcyan", new java.awt.Color(0xffe0ffff, true));
	/**A color with an ARGB value of 0xfffafad2<div style="border:1px solid black;width:40px;height:20px;background-color:#fafad2;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LIGHTGOLDENRODYELLOW= new NamedColor("LIGHTGOLDENRODYELLOW", new java.awt.Color(0xfffafad2, true));
	/**A color with an ARGB value of 0xfffafad2<div style="border:1px solid black;width:40px;height:20px;background-color:#fafad2;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor lightgoldenrodyellow= new NamedColor("lightgoldenrodyellow", new java.awt.Color(0xfffafad2, true));
	/**A color with an ARGB value of 0xffc0c0c0<div style="border:1px solid black;width:40px;height:20px;background-color:#c0c0c0;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LIGHTGRAY= new NamedColor("LIGHTGRAY", new java.awt.Color(0xffc0c0c0, true));
	/**A color with an ARGB value of 0xffc0c0c0<div style="border:1px solid black;width:40px;height:20px;background-color:#c0c0c0;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor lightgray= new NamedColor("lightgray", new java.awt.Color(0xffc0c0c0, true));
	/**A color with an ARGB value of 0xffd3d3d3<div style="border:1px solid black;width:40px;height:20px;background-color:#d3d3d3;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LIGHTGRAY2= new NamedColor("LIGHTGRAY2", new java.awt.Color(0xffd3d3d3, true));
	/**A color with an ARGB value of 0xffd3d3d3<div style="border:1px solid black;width:40px;height:20px;background-color:#d3d3d3;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor lightgray2= new NamedColor("lightgray2", new java.awt.Color(0xffd3d3d3, true));
	/**A color with an ARGB value of 0xff90ee90<div style="border:1px solid black;width:40px;height:20px;background-color:#90ee90;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LIGHTGREEN= new NamedColor("LIGHTGREEN", new java.awt.Color(0xff90ee90, true));
	/**A color with an ARGB value of 0xff90ee90<div style="border:1px solid black;width:40px;height:20px;background-color:#90ee90;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor lightgreen= new NamedColor("lightgreen", new java.awt.Color(0xff90ee90, true));
	/**A color with an ARGB value of 0xffd3d3d3<div style="border:1px solid black;width:40px;height:20px;background-color:#d3d3d3;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LIGHTGREY= new NamedColor("LIGHTGREY", new java.awt.Color(0xffd3d3d3, true));
	/**A color with an ARGB value of 0xffd3d3d3<div style="border:1px solid black;width:40px;height:20px;background-color:#d3d3d3;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor lightgrey= new NamedColor("lightgrey", new java.awt.Color(0xffd3d3d3, true));
	/**A color with an ARGB value of 0xffffb6c1<div style="border:1px solid black;width:40px;height:20px;background-color:#ffb6c1;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LIGHTPINK= new NamedColor("LIGHTPINK", new java.awt.Color(0xffffb6c1, true));
	/**A color with an ARGB value of 0xffffb6c1<div style="border:1px solid black;width:40px;height:20px;background-color:#ffb6c1;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor lightpink= new NamedColor("lightpink", new java.awt.Color(0xffffb6c1, true));
	/**A color with an ARGB value of 0xffffa07a<div style="border:1px solid black;width:40px;height:20px;background-color:#ffa07a;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LIGHTSALMON= new NamedColor("LIGHTSALMON", new java.awt.Color(0xffffa07a, true));
	/**A color with an ARGB value of 0xffffa07a<div style="border:1px solid black;width:40px;height:20px;background-color:#ffa07a;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor lightsalmon= new NamedColor("lightsalmon", new java.awt.Color(0xffffa07a, true));
	/**A color with an ARGB value of 0xff20b2aa<div style="border:1px solid black;width:40px;height:20px;background-color:#20b2aa;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LIGHTSEAGREEN= new NamedColor("LIGHTSEAGREEN", new java.awt.Color(0xff20b2aa, true));
	/**A color with an ARGB value of 0xff20b2aa<div style="border:1px solid black;width:40px;height:20px;background-color:#20b2aa;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor lightseagreen= new NamedColor("lightseagreen", new java.awt.Color(0xff20b2aa, true));
	/**A color with an ARGB value of 0xff87cefa<div style="border:1px solid black;width:40px;height:20px;background-color:#87cefa;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LIGHTSKYBLUE= new NamedColor("LIGHTSKYBLUE", new java.awt.Color(0xff87cefa, true));
	/**A color with an ARGB value of 0xff87cefa<div style="border:1px solid black;width:40px;height:20px;background-color:#87cefa;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor lightskyblue= new NamedColor("lightskyblue", new java.awt.Color(0xff87cefa, true));
	/**A color with an ARGB value of 0xff778899<div style="border:1px solid black;width:40px;height:20px;background-color:#778899;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LIGHTSLATEGRAY= new NamedColor("LIGHTSLATEGRAY", new java.awt.Color(0xff778899, true));
	/**A color with an ARGB value of 0xff778899<div style="border:1px solid black;width:40px;height:20px;background-color:#778899;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor lightslategray= new NamedColor("lightslategray", new java.awt.Color(0xff778899, true));
	/**A color with an ARGB value of 0xff778899<div style="border:1px solid black;width:40px;height:20px;background-color:#778899;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LIGHTSLATEGREY= new NamedColor("LIGHTSLATEGREY", new java.awt.Color(0xff778899, true));
	/**A color with an ARGB value of 0xff778899<div style="border:1px solid black;width:40px;height:20px;background-color:#778899;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor lightslategrey= new NamedColor("lightslategrey", new java.awt.Color(0xff778899, true));
	/**A color with an ARGB value of 0xffb0c4de<div style="border:1px solid black;width:40px;height:20px;background-color:#b0c4de;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LIGHTSTEELBLUE= new NamedColor("LIGHTSTEELBLUE", new java.awt.Color(0xffb0c4de, true));
	/**A color with an ARGB value of 0xffb0c4de<div style="border:1px solid black;width:40px;height:20px;background-color:#b0c4de;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor lightsteelblue= new NamedColor("lightsteelblue", new java.awt.Color(0xffb0c4de, true));
	/**A color with an ARGB value of 0xffffffe0<div style="border:1px solid black;width:40px;height:20px;background-color:#ffffe0;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LIGHTYELLOW= new NamedColor("LIGHTYELLOW", new java.awt.Color(0xffffffe0, true));
	/**A color with an ARGB value of 0xffffffe0<div style="border:1px solid black;width:40px;height:20px;background-color:#ffffe0;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor lightyellow= new NamedColor("lightyellow", new java.awt.Color(0xffffffe0, true));
	/**A color with an ARGB value of 0xff00ff00<div style="border:1px solid black;width:40px;height:20px;background-color:#00ff00;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LIME= new NamedColor("LIME", new java.awt.Color(0xff00ff00, true));
	/**A color with an ARGB value of 0xff00ff00<div style="border:1px solid black;width:40px;height:20px;background-color:#00ff00;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor lime= new NamedColor("lime", new java.awt.Color(0xff00ff00, true));
	/**A color with an ARGB value of 0xff32cd32<div style="border:1px solid black;width:40px;height:20px;background-color:#32cd32;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LIMEGREEN= new NamedColor("LIMEGREEN", new java.awt.Color(0xff32cd32, true));
	/**A color with an ARGB value of 0xff32cd32<div style="border:1px solid black;width:40px;height:20px;background-color:#32cd32;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor limegreen= new NamedColor("limegreen", new java.awt.Color(0xff32cd32, true));
	/**A color with an ARGB value of 0xfffaf0e6<div style="border:1px solid black;width:40px;height:20px;background-color:#faf0e6;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LINEN= new NamedColor("LINEN", new java.awt.Color(0xfffaf0e6, true));
	/**A color with an ARGB value of 0xfffaf0e6<div style="border:1px solid black;width:40px;height:20px;background-color:#faf0e6;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor linen= new NamedColor("linen", new java.awt.Color(0xfffaf0e6, true));
	/**A color with an ARGB value of 0xffff00ff<div style="border:1px solid black;width:40px;height:20px;background-color:#ff00ff;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor MAGENTA= new NamedColor("MAGENTA", new java.awt.Color(0xffff00ff, true));
	/**A color with an ARGB value of 0xffff00ff<div style="border:1px solid black;width:40px;height:20px;background-color:#ff00ff;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor magenta= new NamedColor("magenta", new java.awt.Color(0xffff00ff, true));
	/**A color with an ARGB value of 0xff800000<div style="border:1px solid black;width:40px;height:20px;background-color:#800000;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor MAROON= new NamedColor("MAROON", new java.awt.Color(0xff800000, true));
	/**A color with an ARGB value of 0xff800000<div style="border:1px solid black;width:40px;height:20px;background-color:#800000;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor maroon= new NamedColor("maroon", new java.awt.Color(0xff800000, true));
	/**A color with an ARGB value of 0xff66cdaa<div style="border:1px solid black;width:40px;height:20px;background-color:#66cdaa;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor MEDIUMAQUAMARINE= new NamedColor("MEDIUMAQUAMARINE", new java.awt.Color(0xff66cdaa, true));
	/**A color with an ARGB value of 0xff66cdaa<div style="border:1px solid black;width:40px;height:20px;background-color:#66cdaa;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor mediumaquamarine= new NamedColor("mediumaquamarine", new java.awt.Color(0xff66cdaa, true));
	/**A color with an ARGB value of 0xff0000cd<div style="border:1px solid black;width:40px;height:20px;background-color:#0000cd;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor MEDIUMBLUE= new NamedColor("MEDIUMBLUE", new java.awt.Color(0xff0000cd, true));
	/**A color with an ARGB value of 0xff0000cd<div style="border:1px solid black;width:40px;height:20px;background-color:#0000cd;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor mediumblue= new NamedColor("mediumblue", new java.awt.Color(0xff0000cd, true));
	/**A color with an ARGB value of 0xffba55d3<div style="border:1px solid black;width:40px;height:20px;background-color:#ba55d3;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor MEDIUMORCHID= new NamedColor("MEDIUMORCHID", new java.awt.Color(0xffba55d3, true));
	/**A color with an ARGB value of 0xffba55d3<div style="border:1px solid black;width:40px;height:20px;background-color:#ba55d3;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor mediumorchid= new NamedColor("mediumorchid", new java.awt.Color(0xffba55d3, true));
	/**A color with an ARGB value of 0xff9370db<div style="border:1px solid black;width:40px;height:20px;background-color:#9370db;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor MEDIUMPURPLE= new NamedColor("MEDIUMPURPLE", new java.awt.Color(0xff9370db, true));
	/**A color with an ARGB value of 0xff9370db<div style="border:1px solid black;width:40px;height:20px;background-color:#9370db;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor mediumpurple= new NamedColor("mediumpurple", new java.awt.Color(0xff9370db, true));
	/**A color with an ARGB value of 0xff3cb371<div style="border:1px solid black;width:40px;height:20px;background-color:#3cb371;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor MEDIUMSEAGREEN= new NamedColor("MEDIUMSEAGREEN", new java.awt.Color(0xff3cb371, true));
	/**A color with an ARGB value of 0xff3cb371<div style="border:1px solid black;width:40px;height:20px;background-color:#3cb371;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor mediumseagreen= new NamedColor("mediumseagreen", new java.awt.Color(0xff3cb371, true));
	/**A color with an ARGB value of 0xff7b68ee<div style="border:1px solid black;width:40px;height:20px;background-color:#7b68ee;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor MEDIUMSLATEBLUE= new NamedColor("MEDIUMSLATEBLUE", new java.awt.Color(0xff7b68ee, true));
	/**A color with an ARGB value of 0xff7b68ee<div style="border:1px solid black;width:40px;height:20px;background-color:#7b68ee;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor mediumslateblue= new NamedColor("mediumslateblue", new java.awt.Color(0xff7b68ee, true));
	/**A color with an ARGB value of 0xff00fa9a<div style="border:1px solid black;width:40px;height:20px;background-color:#00fa9a;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor MEDIUMSPRINGGREEN= new NamedColor("MEDIUMSPRINGGREEN", new java.awt.Color(0xff00fa9a, true));
	/**A color with an ARGB value of 0xff00fa9a<div style="border:1px solid black;width:40px;height:20px;background-color:#00fa9a;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor mediumspringgreen= new NamedColor("mediumspringgreen", new java.awt.Color(0xff00fa9a, true));
	/**A color with an ARGB value of 0xff48d1cc<div style="border:1px solid black;width:40px;height:20px;background-color:#48d1cc;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor MEDIUMTURQUOISE= new NamedColor("MEDIUMTURQUOISE", new java.awt.Color(0xff48d1cc, true));
	/**A color with an ARGB value of 0xff48d1cc<div style="border:1px solid black;width:40px;height:20px;background-color:#48d1cc;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor mediumturquoise= new NamedColor("mediumturquoise", new java.awt.Color(0xff48d1cc, true));
	/**A color with an ARGB value of 0xffc71585<div style="border:1px solid black;width:40px;height:20px;background-color:#c71585;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor MEDIUMVIOLETRED= new NamedColor("MEDIUMVIOLETRED", new java.awt.Color(0xffc71585, true));
	/**A color with an ARGB value of 0xffc71585<div style="border:1px solid black;width:40px;height:20px;background-color:#c71585;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor mediumvioletred= new NamedColor("mediumvioletred", new java.awt.Color(0xffc71585, true));
	/**A color with an ARGB value of 0xff191970<div style="border:1px solid black;width:40px;height:20px;background-color:#191970;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor MIDNIGHTBLUE= new NamedColor("MIDNIGHTBLUE", new java.awt.Color(0xff191970, true));
	/**A color with an ARGB value of 0xff191970<div style="border:1px solid black;width:40px;height:20px;background-color:#191970;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor midnightblue= new NamedColor("midnightblue", new java.awt.Color(0xff191970, true));
	/**A color with an ARGB value of 0xfff5fffa<div style="border:1px solid black;width:40px;height:20px;background-color:#f5fffa;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor MINTCREAM= new NamedColor("MINTCREAM", new java.awt.Color(0xfff5fffa, true));
	/**A color with an ARGB value of 0xfff5fffa<div style="border:1px solid black;width:40px;height:20px;background-color:#f5fffa;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor mintcream= new NamedColor("mintcream", new java.awt.Color(0xfff5fffa, true));
	/**A color with an ARGB value of 0xffffe4e1<div style="border:1px solid black;width:40px;height:20px;background-color:#ffe4e1;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor MISTYROSE= new NamedColor("MISTYROSE", new java.awt.Color(0xffffe4e1, true));
	/**A color with an ARGB value of 0xffffe4e1<div style="border:1px solid black;width:40px;height:20px;background-color:#ffe4e1;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor mistyrose= new NamedColor("mistyrose", new java.awt.Color(0xffffe4e1, true));
	/**A color with an ARGB value of 0xffffe4b5<div style="border:1px solid black;width:40px;height:20px;background-color:#ffe4b5;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor MOCCASIN= new NamedColor("MOCCASIN", new java.awt.Color(0xffffe4b5, true));
	/**A color with an ARGB value of 0xffffe4b5<div style="border:1px solid black;width:40px;height:20px;background-color:#ffe4b5;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor moccasin= new NamedColor("moccasin", new java.awt.Color(0xffffe4b5, true));
	/**A color with an ARGB value of 0xffffdead<div style="border:1px solid black;width:40px;height:20px;background-color:#ffdead;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor NAVAJOWHITE= new NamedColor("NAVAJOWHITE", new java.awt.Color(0xffffdead, true));
	/**A color with an ARGB value of 0xffffdead<div style="border:1px solid black;width:40px;height:20px;background-color:#ffdead;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor navajowhite= new NamedColor("navajowhite", new java.awt.Color(0xffffdead, true));
	/**A color with an ARGB value of 0xff000080<div style="border:1px solid black;width:40px;height:20px;background-color:#000080;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor NAVY= new NamedColor("NAVY", new java.awt.Color(0xff000080, true));
	/**A color with an ARGB value of 0xff000080<div style="border:1px solid black;width:40px;height:20px;background-color:#000080;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor navy= new NamedColor("navy", new java.awt.Color(0xff000080, true));
	/**A color with an ARGB value of 0xfffdf5e6<div style="border:1px solid black;width:40px;height:20px;background-color:#fdf5e6;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor OLDLACE= new NamedColor("OLDLACE", new java.awt.Color(0xfffdf5e6, true));
	/**A color with an ARGB value of 0xfffdf5e6<div style="border:1px solid black;width:40px;height:20px;background-color:#fdf5e6;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor oldlace= new NamedColor("oldlace", new java.awt.Color(0xfffdf5e6, true));
	/**A color with an ARGB value of 0xff808000<div style="border:1px solid black;width:40px;height:20px;background-color:#808000;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor OLIVE= new NamedColor("OLIVE", new java.awt.Color(0xff808000, true));
	/**A color with an ARGB value of 0xff808000<div style="border:1px solid black;width:40px;height:20px;background-color:#808000;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor olive= new NamedColor("olive", new java.awt.Color(0xff808000, true));
	/**A color with an ARGB value of 0xff6b8e23<div style="border:1px solid black;width:40px;height:20px;background-color:#6b8e23;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor OLIVEDRAB= new NamedColor("OLIVEDRAB", new java.awt.Color(0xff6b8e23, true));
	/**A color with an ARGB value of 0xff6b8e23<div style="border:1px solid black;width:40px;height:20px;background-color:#6b8e23;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor olivedrab= new NamedColor("olivedrab", new java.awt.Color(0xff6b8e23, true));
	/**A color with an ARGB value of 0xffffa500<div style="border:1px solid black;width:40px;height:20px;background-color:#ffa500;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor ORANGE= new NamedColor("ORANGE", new java.awt.Color(0xffffa500, true));
	/**A color with an ARGB value of 0xffffa500<div style="border:1px solid black;width:40px;height:20px;background-color:#ffa500;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor orange= new NamedColor("orange", new java.awt.Color(0xffffa500, true));
	/**A color with an ARGB value of 0xffffc800<div style="border:1px solid black;width:40px;height:20px;background-color:#ffc800;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor ORANGE2= new NamedColor("ORANGE2", new java.awt.Color(0xffffc800, true));
	/**A color with an ARGB value of 0xffffc800<div style="border:1px solid black;width:40px;height:20px;background-color:#ffc800;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor orange2= new NamedColor("orange2", new java.awt.Color(0xffffc800, true));
	/**A color with an ARGB value of 0xffff4500<div style="border:1px solid black;width:40px;height:20px;background-color:#ff4500;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor ORANGERED= new NamedColor("ORANGERED", new java.awt.Color(0xffff4500, true));
	/**A color with an ARGB value of 0xffff4500<div style="border:1px solid black;width:40px;height:20px;background-color:#ff4500;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor orangered= new NamedColor("orangered", new java.awt.Color(0xffff4500, true));
	/**A color with an ARGB value of 0xffda70d6<div style="border:1px solid black;width:40px;height:20px;background-color:#da70d6;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor ORCHID= new NamedColor("ORCHID", new java.awt.Color(0xffda70d6, true));
	/**A color with an ARGB value of 0xffda70d6<div style="border:1px solid black;width:40px;height:20px;background-color:#da70d6;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor orchid= new NamedColor("orchid", new java.awt.Color(0xffda70d6, true));
	/**A color with an ARGB value of 0xffeee8aa<div style="border:1px solid black;width:40px;height:20px;background-color:#eee8aa;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor PALEGOLDENROD= new NamedColor("PALEGOLDENROD", new java.awt.Color(0xffeee8aa, true));
	/**A color with an ARGB value of 0xffeee8aa<div style="border:1px solid black;width:40px;height:20px;background-color:#eee8aa;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor palegoldenrod= new NamedColor("palegoldenrod", new java.awt.Color(0xffeee8aa, true));
	/**A color with an ARGB value of 0xff98fb98<div style="border:1px solid black;width:40px;height:20px;background-color:#98fb98;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor PALEGREEN= new NamedColor("PALEGREEN", new java.awt.Color(0xff98fb98, true));
	/**A color with an ARGB value of 0xff98fb98<div style="border:1px solid black;width:40px;height:20px;background-color:#98fb98;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor palegreen= new NamedColor("palegreen", new java.awt.Color(0xff98fb98, true));
	/**A color with an ARGB value of 0xffafeeee<div style="border:1px solid black;width:40px;height:20px;background-color:#afeeee;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor PALETURQUOISE= new NamedColor("PALETURQUOISE", new java.awt.Color(0xffafeeee, true));
	/**A color with an ARGB value of 0xffafeeee<div style="border:1px solid black;width:40px;height:20px;background-color:#afeeee;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor paleturquoise= new NamedColor("paleturquoise", new java.awt.Color(0xffafeeee, true));
	/**A color with an ARGB value of 0xffdb7093<div style="border:1px solid black;width:40px;height:20px;background-color:#db7093;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor PALEVIOLETRED= new NamedColor("PALEVIOLETRED", new java.awt.Color(0xffdb7093, true));
	/**A color with an ARGB value of 0xffdb7093<div style="border:1px solid black;width:40px;height:20px;background-color:#db7093;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor palevioletred= new NamedColor("palevioletred", new java.awt.Color(0xffdb7093, true));
	/**A color with an ARGB value of 0xffffefd5<div style="border:1px solid black;width:40px;height:20px;background-color:#ffefd5;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor PAPAYAWHIP= new NamedColor("PAPAYAWHIP", new java.awt.Color(0xffffefd5, true));
	/**A color with an ARGB value of 0xffffefd5<div style="border:1px solid black;width:40px;height:20px;background-color:#ffefd5;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor papayawhip= new NamedColor("papayawhip", new java.awt.Color(0xffffefd5, true));
	/**A color with an ARGB value of 0xffffdab9<div style="border:1px solid black;width:40px;height:20px;background-color:#ffdab9;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor PEACHPUFF= new NamedColor("PEACHPUFF", new java.awt.Color(0xffffdab9, true));
	/**A color with an ARGB value of 0xffffdab9<div style="border:1px solid black;width:40px;height:20px;background-color:#ffdab9;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor peachpuff= new NamedColor("peachpuff", new java.awt.Color(0xffffdab9, true));
	/**A color with an ARGB value of 0xffcd853f<div style="border:1px solid black;width:40px;height:20px;background-color:#cd853f;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor PERU= new NamedColor("PERU", new java.awt.Color(0xffcd853f, true));
	/**A color with an ARGB value of 0xffcd853f<div style="border:1px solid black;width:40px;height:20px;background-color:#cd853f;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor peru= new NamedColor("peru", new java.awt.Color(0xffcd853f, true));
	/**A color with an ARGB value of 0xffffafaf<div style="border:1px solid black;width:40px;height:20px;background-color:#ffafaf;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor PINK= new NamedColor("PINK", new java.awt.Color(0xffffafaf, true));
	/**A color with an ARGB value of 0xffffafaf<div style="border:1px solid black;width:40px;height:20px;background-color:#ffafaf;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor pink= new NamedColor("pink", new java.awt.Color(0xffffafaf, true));
	/**A color with an ARGB value of 0xffffc0cb<div style="border:1px solid black;width:40px;height:20px;background-color:#ffc0cb;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor PINK2= new NamedColor("PINK2", new java.awt.Color(0xffffc0cb, true));
	/**A color with an ARGB value of 0xffffc0cb<div style="border:1px solid black;width:40px;height:20px;background-color:#ffc0cb;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor pink2= new NamedColor("pink2", new java.awt.Color(0xffffc0cb, true));
	/**A color with an ARGB value of 0xffdda0dd<div style="border:1px solid black;width:40px;height:20px;background-color:#dda0dd;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor PLUM= new NamedColor("PLUM", new java.awt.Color(0xffdda0dd, true));
	/**A color with an ARGB value of 0xffdda0dd<div style="border:1px solid black;width:40px;height:20px;background-color:#dda0dd;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor plum= new NamedColor("plum", new java.awt.Color(0xffdda0dd, true));
	/**A color with an ARGB value of 0xffb0e0e6<div style="border:1px solid black;width:40px;height:20px;background-color:#b0e0e6;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor POWDERBLUE= new NamedColor("POWDERBLUE", new java.awt.Color(0xffb0e0e6, true));
	/**A color with an ARGB value of 0xffb0e0e6<div style="border:1px solid black;width:40px;height:20px;background-color:#b0e0e6;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor powderblue= new NamedColor("powderblue", new java.awt.Color(0xffb0e0e6, true));
	/**A color with an ARGB value of 0xff800080<div style="border:1px solid black;width:40px;height:20px;background-color:#800080;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor PURPLE= new NamedColor("PURPLE", new java.awt.Color(0xff800080, true));
	/**A color with an ARGB value of 0xff800080<div style="border:1px solid black;width:40px;height:20px;background-color:#800080;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor purple= new NamedColor("purple", new java.awt.Color(0xff800080, true));
	/**A color with an ARGB value of 0xffff0000<div style="border:1px solid black;width:40px;height:20px;background-color:#ff0000;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor RED= new NamedColor("RED", new java.awt.Color(0xffff0000, true));
	/**A color with an ARGB value of 0xffff0000<div style="border:1px solid black;width:40px;height:20px;background-color:#ff0000;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor red= new NamedColor("red", new java.awt.Color(0xffff0000, true));
	/**A color with an ARGB value of 0xffbc8f8f<div style="border:1px solid black;width:40px;height:20px;background-color:#bc8f8f;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor ROSYBROWN= new NamedColor("ROSYBROWN", new java.awt.Color(0xffbc8f8f, true));
	/**A color with an ARGB value of 0xffbc8f8f<div style="border:1px solid black;width:40px;height:20px;background-color:#bc8f8f;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor rosybrown= new NamedColor("rosybrown", new java.awt.Color(0xffbc8f8f, true));
	/**A color with an ARGB value of 0xff4169e1<div style="border:1px solid black;width:40px;height:20px;background-color:#4169e1;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor ROYALBLUE= new NamedColor("ROYALBLUE", new java.awt.Color(0xff4169e1, true));
	/**A color with an ARGB value of 0xff4169e1<div style="border:1px solid black;width:40px;height:20px;background-color:#4169e1;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor royalblue= new NamedColor("royalblue", new java.awt.Color(0xff4169e1, true));
	/**A color with an ARGB value of 0xff8b4513<div style="border:1px solid black;width:40px;height:20px;background-color:#8b4513;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor SADDLEBROWN= new NamedColor("SADDLEBROWN", new java.awt.Color(0xff8b4513, true));
	/**A color with an ARGB value of 0xff8b4513<div style="border:1px solid black;width:40px;height:20px;background-color:#8b4513;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor saddlebrown= new NamedColor("saddlebrown", new java.awt.Color(0xff8b4513, true));
	/**A color with an ARGB value of 0xfffa8072<div style="border:1px solid black;width:40px;height:20px;background-color:#fa8072;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor SALMON= new NamedColor("SALMON", new java.awt.Color(0xfffa8072, true));
	/**A color with an ARGB value of 0xfffa8072<div style="border:1px solid black;width:40px;height:20px;background-color:#fa8072;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor salmon= new NamedColor("salmon", new java.awt.Color(0xfffa8072, true));
	/**A color with an ARGB value of 0xfff4a460<div style="border:1px solid black;width:40px;height:20px;background-color:#f4a460;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor SANDYBROWN= new NamedColor("SANDYBROWN", new java.awt.Color(0xfff4a460, true));
	/**A color with an ARGB value of 0xfff4a460<div style="border:1px solid black;width:40px;height:20px;background-color:#f4a460;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor sandybrown= new NamedColor("sandybrown", new java.awt.Color(0xfff4a460, true));
	/**A color with an ARGB value of 0xff2e8b57<div style="border:1px solid black;width:40px;height:20px;background-color:#2e8b57;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor SEAGREEN= new NamedColor("SEAGREEN", new java.awt.Color(0xff2e8b57, true));
	/**A color with an ARGB value of 0xff2e8b57<div style="border:1px solid black;width:40px;height:20px;background-color:#2e8b57;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor seagreen= new NamedColor("seagreen", new java.awt.Color(0xff2e8b57, true));
	/**A color with an ARGB value of 0xfffff5ee<div style="border:1px solid black;width:40px;height:20px;background-color:#fff5ee;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor SEASHELL= new NamedColor("SEASHELL", new java.awt.Color(0xfffff5ee, true));
	/**A color with an ARGB value of 0xfffff5ee<div style="border:1px solid black;width:40px;height:20px;background-color:#fff5ee;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor seashell= new NamedColor("seashell", new java.awt.Color(0xfffff5ee, true));
	/**A color with an ARGB value of 0xffa0522d<div style="border:1px solid black;width:40px;height:20px;background-color:#a0522d;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor SIENNA= new NamedColor("SIENNA", new java.awt.Color(0xffa0522d, true));
	/**A color with an ARGB value of 0xffa0522d<div style="border:1px solid black;width:40px;height:20px;background-color:#a0522d;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor sienna= new NamedColor("sienna", new java.awt.Color(0xffa0522d, true));
	/**A color with an ARGB value of 0xffc0c0c0<div style="border:1px solid black;width:40px;height:20px;background-color:#c0c0c0;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor SILVER= new NamedColor("SILVER", new java.awt.Color(0xffc0c0c0, true));
	/**A color with an ARGB value of 0xffc0c0c0<div style="border:1px solid black;width:40px;height:20px;background-color:#c0c0c0;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor silver= new NamedColor("silver", new java.awt.Color(0xffc0c0c0, true));
	/**A color with an ARGB value of 0xff87ceeb<div style="border:1px solid black;width:40px;height:20px;background-color:#87ceeb;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor SKYBLUE= new NamedColor("SKYBLUE", new java.awt.Color(0xff87ceeb, true));
	/**A color with an ARGB value of 0xff87ceeb<div style="border:1px solid black;width:40px;height:20px;background-color:#87ceeb;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor skyblue= new NamedColor("skyblue", new java.awt.Color(0xff87ceeb, true));
	/**A color with an ARGB value of 0xff6a5acd<div style="border:1px solid black;width:40px;height:20px;background-color:#6a5acd;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor SLATEBLUE= new NamedColor("SLATEBLUE", new java.awt.Color(0xff6a5acd, true));
	/**A color with an ARGB value of 0xff6a5acd<div style="border:1px solid black;width:40px;height:20px;background-color:#6a5acd;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor slateblue= new NamedColor("slateblue", new java.awt.Color(0xff6a5acd, true));
	/**A color with an ARGB value of 0xff708090<div style="border:1px solid black;width:40px;height:20px;background-color:#708090;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor SLATEGRAY= new NamedColor("SLATEGRAY", new java.awt.Color(0xff708090, true));
	/**A color with an ARGB value of 0xff708090<div style="border:1px solid black;width:40px;height:20px;background-color:#708090;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor slategray= new NamedColor("slategray", new java.awt.Color(0xff708090, true));
	/**A color with an ARGB value of 0xff708090<div style="border:1px solid black;width:40px;height:20px;background-color:#708090;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor SLATEGREY= new NamedColor("SLATEGREY", new java.awt.Color(0xff708090, true));
	/**A color with an ARGB value of 0xff708090<div style="border:1px solid black;width:40px;height:20px;background-color:#708090;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor slategrey= new NamedColor("slategrey", new java.awt.Color(0xff708090, true));
	/**A color with an ARGB value of 0xfffffafa<div style="border:1px solid black;width:40px;height:20px;background-color:#fffafa;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor SNOW= new NamedColor("SNOW", new java.awt.Color(0xfffffafa, true));
	/**A color with an ARGB value of 0xfffffafa<div style="border:1px solid black;width:40px;height:20px;background-color:#fffafa;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor snow= new NamedColor("snow", new java.awt.Color(0xfffffafa, true));
	/**A color with an ARGB value of 0xff00ff7f<div style="border:1px solid black;width:40px;height:20px;background-color:#00ff7f;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor SPRINGGREEN= new NamedColor("SPRINGGREEN", new java.awt.Color(0xff00ff7f, true));
	/**A color with an ARGB value of 0xff00ff7f<div style="border:1px solid black;width:40px;height:20px;background-color:#00ff7f;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor springgreen= new NamedColor("springgreen", new java.awt.Color(0xff00ff7f, true));
	/**A color with an ARGB value of 0xff4682b4<div style="border:1px solid black;width:40px;height:20px;background-color:#4682b4;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor STEELBLUE= new NamedColor("STEELBLUE", new java.awt.Color(0xff4682b4, true));
	/**A color with an ARGB value of 0xff4682b4<div style="border:1px solid black;width:40px;height:20px;background-color:#4682b4;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor steelblue= new NamedColor("steelblue", new java.awt.Color(0xff4682b4, true));
	/**A color with an ARGB value of 0xffd2b48c<div style="border:1px solid black;width:40px;height:20px;background-color:#d2b48c;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor TAN= new NamedColor("TAN", new java.awt.Color(0xffd2b48c, true));
	/**A color with an ARGB value of 0xffd2b48c<div style="border:1px solid black;width:40px;height:20px;background-color:#d2b48c;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor tan= new NamedColor("tan", new java.awt.Color(0xffd2b48c, true));
	/**A color with an ARGB value of 0xff008080<div style="border:1px solid black;width:40px;height:20px;background-color:#008080;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor TEAL= new NamedColor("TEAL", new java.awt.Color(0xff008080, true));
	/**A color with an ARGB value of 0xff008080<div style="border:1px solid black;width:40px;height:20px;background-color:#008080;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor teal= new NamedColor("teal", new java.awt.Color(0xff008080, true));
	/**A color with an ARGB value of 0xffd8bfd8<div style="border:1px solid black;width:40px;height:20px;background-color:#d8bfd8;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor THISTLE= new NamedColor("THISTLE", new java.awt.Color(0xffd8bfd8, true));
	/**A color with an ARGB value of 0xffd8bfd8<div style="border:1px solid black;width:40px;height:20px;background-color:#d8bfd8;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor thistle= new NamedColor("thistle", new java.awt.Color(0xffd8bfd8, true));
	/**A color with an ARGB value of 0xffff6347<div style="border:1px solid black;width:40px;height:20px;background-color:#ff6347;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor TOMATO= new NamedColor("TOMATO", new java.awt.Color(0xffff6347, true));
	/**A color with an ARGB value of 0xffff6347<div style="border:1px solid black;width:40px;height:20px;background-color:#ff6347;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor tomato= new NamedColor("tomato", new java.awt.Color(0xffff6347, true));
	/**A color with an ARGB value of 0x00000000<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(0,0,0,0.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor TRANSPARENT= new NamedColor("TRANSPARENT", new java.awt.Color(0x00000000, true));
	/**A color with an ARGB value of 0x00000000<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(0,0,0,0.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor transparent= new NamedColor("transparent", new java.awt.Color(0x00000000, true));
	/**A color with an ARGB value of 0xff40e0d0<div style="border:1px solid black;width:40px;height:20px;background-color:#40e0d0;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor TURQUOISE= new NamedColor("TURQUOISE", new java.awt.Color(0xff40e0d0, true));
	/**A color with an ARGB value of 0xff40e0d0<div style="border:1px solid black;width:40px;height:20px;background-color:#40e0d0;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor turquoise= new NamedColor("turquoise", new java.awt.Color(0xff40e0d0, true));
	/**A color with an ARGB value of 0xffee82ee<div style="border:1px solid black;width:40px;height:20px;background-color:#ee82ee;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor VIOLET= new NamedColor("VIOLET", new java.awt.Color(0xffee82ee, true));
	/**A color with an ARGB value of 0xffee82ee<div style="border:1px solid black;width:40px;height:20px;background-color:#ee82ee;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor violet= new NamedColor("violet", new java.awt.Color(0xffee82ee, true));
	/**A color with an ARGB value of 0xfff5deb3<div style="border:1px solid black;width:40px;height:20px;background-color:#f5deb3;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor WHEAT= new NamedColor("WHEAT", new java.awt.Color(0xfff5deb3, true));
	/**A color with an ARGB value of 0xfff5deb3<div style="border:1px solid black;width:40px;height:20px;background-color:#f5deb3;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor wheat= new NamedColor("wheat", new java.awt.Color(0xfff5deb3, true));
	/**A color with an ARGB value of 0xffffffff<div style="border:1px solid black;width:40px;height:20px;background-color:#ffffff;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor WHITE= new NamedColor("WHITE", new java.awt.Color(0xffffffff, true));
	/**A color with an ARGB value of 0xffffffff<div style="border:1px solid black;width:40px;height:20px;background-color:#ffffff;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor white= new NamedColor("white", new java.awt.Color(0xffffffff, true));
	/**A color with an ARGB value of 0xfff5f5f5<div style="border:1px solid black;width:40px;height:20px;background-color:#f5f5f5;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor WHITESMOKE= new NamedColor("WHITESMOKE", new java.awt.Color(0xfff5f5f5, true));
	/**A color with an ARGB value of 0xfff5f5f5<div style="border:1px solid black;width:40px;height:20px;background-color:#f5f5f5;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor whitesmoke= new NamedColor("whitesmoke", new java.awt.Color(0xfff5f5f5, true));
	/**A color with an ARGB value of 0xffffff00<div style="border:1px solid black;width:40px;height:20px;background-color:#ffff00;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor YELLOW= new NamedColor("YELLOW", new java.awt.Color(0xffffff00, true));
	/**A color with an ARGB value of 0xffffff00<div style="border:1px solid black;width:40px;height:20px;background-color:#ffff00;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor yellow= new NamedColor("yellow", new java.awt.Color(0xffffff00, true));
	/**A color with an ARGB value of 0xff9acd32<div style="border:1px solid black;width:40px;height:20px;background-color:#9acd32;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor YELLOWGREEN= new NamedColor("YELLOWGREEN", new java.awt.Color(0xff9acd32, true));
	/**A color with an ARGB value of 0xff9acd32<div style="border:1px solid black;width:40px;height:20px;background-color:#9acd32;float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor yellowgreen= new NamedColor("yellowgreen", new java.awt.Color(0xff9acd32, true));
}
