package tools.colors;

@javax.annotation.Generated(value = {"dashboard.Main"}, date = "Friday, August 19, 2016 1:03:16 AM UTC")
@Deprecated public final class NamedColorConstants
{
	private NamedColorConstants(){}
	@Deprecated/**A color with an ARGB value of 0xfff0f8ff<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(240,248,255,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor AliceBlue            = new NamedColor("AliceBlue",            new java.awt.Color(0xfff0f8ff, true));
	@Deprecated/**A color with an ARGB value of 0xfffaebd7<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(250,235,215,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor AntiqueWhite         = new NamedColor("AntiqueWhite",         new java.awt.Color(0xfffaebd7, true));
	@Deprecated/**A color with an ARGB value of 0xff00ffff<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(000,255,255,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Aqua                 = new NamedColor("Aqua",                 new java.awt.Color(0xff00ffff, true));
	@Deprecated/**A color with an ARGB value of 0xff7fffd4<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(127,255,212,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Aquamarine           = new NamedColor("Aquamarine",           new java.awt.Color(0xff7fffd4, true));
	@Deprecated/**A color with an ARGB value of 0xfff0ffff<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(240,255,255,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Azure                = new NamedColor("Azure",                new java.awt.Color(0xfff0ffff, true));
	@Deprecated/**A color with an ARGB value of 0xfff5f5dc<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(245,245,220,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Beige                = new NamedColor("Beige",                new java.awt.Color(0xfff5f5dc, true));
	@Deprecated/**A color with an ARGB value of 0xffffe4c4<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(255,228,196,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Bisque               = new NamedColor("Bisque",               new java.awt.Color(0xffffe4c4, true));
	@Deprecated/**A color with an ARGB value of 0xff000000<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(000,000,000,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Black                = new NamedColor("Black",                new java.awt.Color(0xff000000, true));
	@Deprecated/**A color with an ARGB value of 0xffffebcd<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(255,235,205,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor BlanchedAlmond       = new NamedColor("BlanchedAlmond",       new java.awt.Color(0xffffebcd, true));
	@Deprecated/**A color with an ARGB value of 0xff0000ff<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(000,000,255,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Blue                 = new NamedColor("Blue",                 new java.awt.Color(0xff0000ff, true));
	@Deprecated/**A color with an ARGB value of 0xff8a2be2<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(138,043,226,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor BlueViolet           = new NamedColor("BlueViolet",           new java.awt.Color(0xff8a2be2, true));
	@Deprecated/**A color with an ARGB value of 0xffa52a2a<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(165,042,042,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Brown                = new NamedColor("Brown",                new java.awt.Color(0xffa52a2a, true));
	@Deprecated/**A color with an ARGB value of 0xffdeb887<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(222,184,135,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor BurlyWood            = new NamedColor("BurlyWood",            new java.awt.Color(0xffdeb887, true));
	@Deprecated/**A color with an ARGB value of 0xff5f9ea0<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(095,158,160,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor CadetBlue            = new NamedColor("CadetBlue",            new java.awt.Color(0xff5f9ea0, true));
	@Deprecated/**A color with an ARGB value of 0xff7fff00<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(127,255,000,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Chartreuse           = new NamedColor("Chartreuse",           new java.awt.Color(0xff7fff00, true));
	@Deprecated/**A color with an ARGB value of 0xffd2691e<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(210,105,030,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Chocolate            = new NamedColor("Chocolate",            new java.awt.Color(0xffd2691e, true));
	@Deprecated/**A color with an ARGB value of 0xffff7f50<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(255,127,080,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Coral                = new NamedColor("Coral",                new java.awt.Color(0xffff7f50, true));
	@Deprecated/**A color with an ARGB value of 0xff6495ed<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(100,149,237,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor CornflowerBlue       = new NamedColor("CornflowerBlue",       new java.awt.Color(0xff6495ed, true));
	@Deprecated/**A color with an ARGB value of 0xfffff8dc<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(255,248,220,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Cornsilk             = new NamedColor("Cornsilk",             new java.awt.Color(0xfffff8dc, true));
	@Deprecated/**A color with an ARGB value of 0xffdc143c<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(220,020,060,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Crimson              = new NamedColor("Crimson",              new java.awt.Color(0xffdc143c, true));
	@Deprecated/**A color with an ARGB value of 0xff00ffff<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(000,255,255,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Cyan                 = new NamedColor("Cyan",                 new java.awt.Color(0xff00ffff, true));
	@Deprecated/**A color with an ARGB value of 0xff00008b<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(000,000,139,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DarkBlue             = new NamedColor("DarkBlue",             new java.awt.Color(0xff00008b, true));
	@Deprecated/**A color with an ARGB value of 0xff008b8b<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(000,139,139,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DarkCyan             = new NamedColor("DarkCyan",             new java.awt.Color(0xff008b8b, true));
	@Deprecated/**A color with an ARGB value of 0xffb8860b<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(184,134,011,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DarkGoldenRod        = new NamedColor("DarkGoldenRod",        new java.awt.Color(0xffb8860b, true));
	@Deprecated/**A color with an ARGB value of 0xffa9a9a9<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(169,169,169,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DarkGray             = new NamedColor("DarkGray",             new java.awt.Color(0xffa9a9a9, true));
	@Deprecated/**A color with an ARGB value of 0xffa9a9a9<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(169,169,169,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DarkGrey             = new NamedColor("DarkGrey",             new java.awt.Color(0xffa9a9a9, true));
	@Deprecated/**A color with an ARGB value of 0xff006400<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(000,100,000,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DarkGreen            = new NamedColor("DarkGreen",            new java.awt.Color(0xff006400, true));
	@Deprecated/**A color with an ARGB value of 0xffbdb76b<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(189,183,107,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DarkKhaki            = new NamedColor("DarkKhaki",            new java.awt.Color(0xffbdb76b, true));
	@Deprecated/**A color with an ARGB value of 0xff8b008b<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(139,000,139,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DarkMagenta          = new NamedColor("DarkMagenta",          new java.awt.Color(0xff8b008b, true));
	@Deprecated/**A color with an ARGB value of 0xff556b2f<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(085,107,047,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DarkOliveGreen       = new NamedColor("DarkOliveGreen",       new java.awt.Color(0xff556b2f, true));
	@Deprecated/**A color with an ARGB value of 0xffff8c00<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(255,140,000,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DarkOrange           = new NamedColor("DarkOrange",           new java.awt.Color(0xffff8c00, true));
	@Deprecated/**A color with an ARGB value of 0xff9932cc<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(153,050,204,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DarkOrchid           = new NamedColor("DarkOrchid",           new java.awt.Color(0xff9932cc, true));
	@Deprecated/**A color with an ARGB value of 0xff8b0000<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(139,000,000,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DarkRed              = new NamedColor("DarkRed",              new java.awt.Color(0xff8b0000, true));
	@Deprecated/**A color with an ARGB value of 0xffe9967a<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(233,150,122,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DarkSalmon           = new NamedColor("DarkSalmon",           new java.awt.Color(0xffe9967a, true));
	@Deprecated/**A color with an ARGB value of 0xff8fbc8f<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(143,188,143,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DarkSeaGreen         = new NamedColor("DarkSeaGreen",         new java.awt.Color(0xff8fbc8f, true));
	@Deprecated/**A color with an ARGB value of 0xff483d8b<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(072,061,139,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DarkSlateBlue        = new NamedColor("DarkSlateBlue",        new java.awt.Color(0xff483d8b, true));
	@Deprecated/**A color with an ARGB value of 0xff2f4f4f<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(047,079,079,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DarkSlateGray        = new NamedColor("DarkSlateGray",        new java.awt.Color(0xff2f4f4f, true));
	@Deprecated/**A color with an ARGB value of 0xff2f4f4f<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(047,079,079,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DarkSlateGrey        = new NamedColor("DarkSlateGrey",        new java.awt.Color(0xff2f4f4f, true));
	@Deprecated/**A color with an ARGB value of 0xff00ced1<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(000,206,209,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DarkTurquoise        = new NamedColor("DarkTurquoise",        new java.awt.Color(0xff00ced1, true));
	@Deprecated/**A color with an ARGB value of 0xff9400d3<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(148,000,211,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DarkViolet           = new NamedColor("DarkViolet",           new java.awt.Color(0xff9400d3, true));
	@Deprecated/**A color with an ARGB value of 0xffff1493<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(255,020,147,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DeepPink             = new NamedColor("DeepPink",             new java.awt.Color(0xffff1493, true));
	@Deprecated/**A color with an ARGB value of 0xff00bfff<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(000,191,255,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DeepSkyBlue          = new NamedColor("DeepSkyBlue",          new java.awt.Color(0xff00bfff, true));
	@Deprecated/**A color with an ARGB value of 0xff696969<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(105,105,105,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DimGray              = new NamedColor("DimGray",              new java.awt.Color(0xff696969, true));
	@Deprecated/**A color with an ARGB value of 0xff696969<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(105,105,105,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DimGrey              = new NamedColor("DimGrey",              new java.awt.Color(0xff696969, true));
	@Deprecated/**A color with an ARGB value of 0xff1e90ff<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(030,144,255,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor DodgerBlue           = new NamedColor("DodgerBlue",           new java.awt.Color(0xff1e90ff, true));
	@Deprecated/**A color with an ARGB value of 0xffb22222<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(178,034,034,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor FireBrick            = new NamedColor("FireBrick",            new java.awt.Color(0xffb22222, true));
	@Deprecated/**A color with an ARGB value of 0xfffffaf0<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(255,250,240,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor FloralWhite          = new NamedColor("FloralWhite",          new java.awt.Color(0xfffffaf0, true));
	@Deprecated/**A color with an ARGB value of 0xff228b22<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(034,139,034,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor ForestGreen          = new NamedColor("ForestGreen",          new java.awt.Color(0xff228b22, true));
	@Deprecated/**A color with an ARGB value of 0xffff00ff<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(255,000,255,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Fuchsia              = new NamedColor("Fuchsia",              new java.awt.Color(0xffff00ff, true));
	@Deprecated/**A color with an ARGB value of 0xffdcdcdc<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(220,220,220,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Gainsboro            = new NamedColor("Gainsboro",            new java.awt.Color(0xffdcdcdc, true));
	@Deprecated/**A color with an ARGB value of 0xfff8f8ff<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(248,248,255,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor GhostWhite           = new NamedColor("GhostWhite",           new java.awt.Color(0xfff8f8ff, true));
	@Deprecated/**A color with an ARGB value of 0xffffd700<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(255,215,000,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Gold                 = new NamedColor("Gold",                 new java.awt.Color(0xffffd700, true));
	@Deprecated/**A color with an ARGB value of 0xffdaa520<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(218,165,032,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor GoldenRod            = new NamedColor("GoldenRod",            new java.awt.Color(0xffdaa520, true));
	@Deprecated/**A color with an ARGB value of 0xff808080<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(128,128,128,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Gray                 = new NamedColor("Gray",                 new java.awt.Color(0xff808080, true));
	@Deprecated/**A color with an ARGB value of 0xff808080<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(128,128,128,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Grey                 = new NamedColor("Grey",                 new java.awt.Color(0xff808080, true));
	@Deprecated/**A color with an ARGB value of 0xff008000<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(000,128,000,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Green                = new NamedColor("Green",                new java.awt.Color(0xff008000, true));
	@Deprecated/**A color with an ARGB value of 0xffadff2f<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(173,255,047,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor GreenYellow          = new NamedColor("GreenYellow",          new java.awt.Color(0xffadff2f, true));
	@Deprecated/**A color with an ARGB value of 0xfff0fff0<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(240,255,240,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor HoneyDew             = new NamedColor("HoneyDew",             new java.awt.Color(0xfff0fff0, true));
	@Deprecated/**A color with an ARGB value of 0xffff69b4<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(255,105,180,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor HotPink              = new NamedColor("HotPink",              new java.awt.Color(0xffff69b4, true));
	@Deprecated/**A color with an ARGB value of 0xffcd5c5c<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(205,092,092,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor IndianRed            = new NamedColor("IndianRed",            new java.awt.Color(0xffcd5c5c, true));
	@Deprecated/**A color with an ARGB value of 0xff4b0082<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(075,000,130,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Indigo               = new NamedColor("Indigo",               new java.awt.Color(0xff4b0082, true));
	@Deprecated/**A color with an ARGB value of 0xfffffff0<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(255,255,240,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Ivory                = new NamedColor("Ivory",                new java.awt.Color(0xfffffff0, true));
	@Deprecated/**A color with an ARGB value of 0xfff0e68c<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(240,230,140,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Khaki                = new NamedColor("Khaki",                new java.awt.Color(0xfff0e68c, true));
	@Deprecated/**A color with an ARGB value of 0xffe6e6fa<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(230,230,250,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Lavender             = new NamedColor("Lavender",             new java.awt.Color(0xffe6e6fa, true));
	@Deprecated/**A color with an ARGB value of 0xfffff0f5<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(255,240,245,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LavenderBlush        = new NamedColor("LavenderBlush",        new java.awt.Color(0xfffff0f5, true));
	@Deprecated/**A color with an ARGB value of 0xff7cfc00<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(124,252,000,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LawnGreen            = new NamedColor("LawnGreen",            new java.awt.Color(0xff7cfc00, true));
	@Deprecated/**A color with an ARGB value of 0xfffffacd<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(255,250,205,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LemonChiffon         = new NamedColor("LemonChiffon",         new java.awt.Color(0xfffffacd, true));
	@Deprecated/**A color with an ARGB value of 0xffadd8e6<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(173,216,230,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LightBlue            = new NamedColor("LightBlue",            new java.awt.Color(0xffadd8e6, true));
	@Deprecated/**A color with an ARGB value of 0xfff08080<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(240,128,128,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LightCoral           = new NamedColor("LightCoral",           new java.awt.Color(0xfff08080, true));
	@Deprecated/**A color with an ARGB value of 0xffe0ffff<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(224,255,255,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LightCyan            = new NamedColor("LightCyan",            new java.awt.Color(0xffe0ffff, true));
	@Deprecated/**A color with an ARGB value of 0xfffafad2<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(250,250,210,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LightGoldenRodYellow = new NamedColor("LightGoldenRodYellow", new java.awt.Color(0xfffafad2, true));
	@Deprecated/**A color with an ARGB value of 0xffd3d3d3<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(211,211,211,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LightGray            = new NamedColor("LightGray",            new java.awt.Color(0xffd3d3d3, true));
	@Deprecated/**A color with an ARGB value of 0xffd3d3d3<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(211,211,211,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LightGrey            = new NamedColor("LightGrey",            new java.awt.Color(0xffd3d3d3, true));
	@Deprecated/**A color with an ARGB value of 0xff90ee90<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(144,238,144,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LightGreen           = new NamedColor("LightGreen",           new java.awt.Color(0xff90ee90, true));
	@Deprecated/**A color with an ARGB value of 0xffffb6c1<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(255,182,193,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LightPink            = new NamedColor("LightPink",            new java.awt.Color(0xffffb6c1, true));
	@Deprecated/**A color with an ARGB value of 0xffffa07a<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(255,160,122,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LightSalmon          = new NamedColor("LightSalmon",          new java.awt.Color(0xffffa07a, true));
	@Deprecated/**A color with an ARGB value of 0xff20b2aa<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(032,178,170,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LightSeaGreen        = new NamedColor("LightSeaGreen",        new java.awt.Color(0xff20b2aa, true));
	@Deprecated/**A color with an ARGB value of 0xff87cefa<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(135,206,250,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LightSkyBlue         = new NamedColor("LightSkyBlue",         new java.awt.Color(0xff87cefa, true));
	@Deprecated/**A color with an ARGB value of 0xff778899<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(119,136,153,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LightSlateGray       = new NamedColor("LightSlateGray",       new java.awt.Color(0xff778899, true));
	@Deprecated/**A color with an ARGB value of 0xff778899<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(119,136,153,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LightSlateGrey       = new NamedColor("LightSlateGrey",       new java.awt.Color(0xff778899, true));
	@Deprecated/**A color with an ARGB value of 0xffb0c4de<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(176,196,222,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LightSteelBlue       = new NamedColor("LightSteelBlue",       new java.awt.Color(0xffb0c4de, true));
	@Deprecated/**A color with an ARGB value of 0xffffffe0<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(255,255,224,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LightYellow          = new NamedColor("LightYellow",          new java.awt.Color(0xffffffe0, true));
	@Deprecated/**A color with an ARGB value of 0xff00ff00<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(000,255,000,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Lime                 = new NamedColor("Lime",                 new java.awt.Color(0xff00ff00, true));
	@Deprecated/**A color with an ARGB value of 0xff32cd32<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(050,205,050,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor LimeGreen            = new NamedColor("LimeGreen",            new java.awt.Color(0xff32cd32, true));
	@Deprecated/**A color with an ARGB value of 0xfffaf0e6<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(250,240,230,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Linen                = new NamedColor("Linen",                new java.awt.Color(0xfffaf0e6, true));
	@Deprecated/**A color with an ARGB value of 0xffff00ff<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(255,000,255,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Magenta              = new NamedColor("Magenta",              new java.awt.Color(0xffff00ff, true));
	@Deprecated/**A color with an ARGB value of 0xff800000<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(128,000,000,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Maroon               = new NamedColor("Maroon",               new java.awt.Color(0xff800000, true));
	@Deprecated/**A color with an ARGB value of 0xff66cdaa<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(102,205,170,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor MediumAquaMarine     = new NamedColor("MediumAquaMarine",     new java.awt.Color(0xff66cdaa, true));
	@Deprecated/**A color with an ARGB value of 0xff0000cd<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(000,000,205,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor MediumBlue           = new NamedColor("MediumBlue",           new java.awt.Color(0xff0000cd, true));
	@Deprecated/**A color with an ARGB value of 0xffba55d3<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(186,085,211,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor MediumOrchid         = new NamedColor("MediumOrchid",         new java.awt.Color(0xffba55d3, true));
	@Deprecated/**A color with an ARGB value of 0xff9370db<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(147,112,219,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor MediumPurple         = new NamedColor("MediumPurple",         new java.awt.Color(0xff9370db, true));
	@Deprecated/**A color with an ARGB value of 0xff3cb371<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(060,179,113,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor MediumSeaGreen       = new NamedColor("MediumSeaGreen",       new java.awt.Color(0xff3cb371, true));
	@Deprecated/**A color with an ARGB value of 0xff7b68ee<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(123,104,238,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor MediumSlateBlue      = new NamedColor("MediumSlateBlue",      new java.awt.Color(0xff7b68ee, true));
	@Deprecated/**A color with an ARGB value of 0xff00fa9a<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(000,250,154,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor MediumSpringGreen    = new NamedColor("MediumSpringGreen",    new java.awt.Color(0xff00fa9a, true));
	@Deprecated/**A color with an ARGB value of 0xff48d1cc<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(072,209,204,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor MediumTurquoise      = new NamedColor("MediumTurquoise",      new java.awt.Color(0xff48d1cc, true));
	@Deprecated/**A color with an ARGB value of 0xffc71585<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(199,021,133,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor MediumVioletRed      = new NamedColor("MediumVioletRed",      new java.awt.Color(0xffc71585, true));
	@Deprecated/**A color with an ARGB value of 0xff191970<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(025,025,112,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor MidnightBlue         = new NamedColor("MidnightBlue",         new java.awt.Color(0xff191970, true));
	@Deprecated/**A color with an ARGB value of 0xfff5fffa<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(245,255,250,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor MintCream            = new NamedColor("MintCream",            new java.awt.Color(0xfff5fffa, true));
	@Deprecated/**A color with an ARGB value of 0xffffe4e1<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(255,228,225,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor MistyRose            = new NamedColor("MistyRose",            new java.awt.Color(0xffffe4e1, true));
	@Deprecated/**A color with an ARGB value of 0xffffe4b5<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(255,228,181,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Moccasin             = new NamedColor("Moccasin",             new java.awt.Color(0xffffe4b5, true));
	@Deprecated/**A color with an ARGB value of 0xffffdead<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(255,222,173,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor NavajoWhite          = new NamedColor("NavajoWhite",          new java.awt.Color(0xffffdead, true));
	@Deprecated/**A color with an ARGB value of 0xff000080<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(000,000,128,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Navy                 = new NamedColor("Navy",                 new java.awt.Color(0xff000080, true));
	@Deprecated/**A color with an ARGB value of 0xfffdf5e6<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(253,245,230,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor OldLace              = new NamedColor("OldLace",              new java.awt.Color(0xfffdf5e6, true));
	@Deprecated/**A color with an ARGB value of 0xff808000<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(128,128,000,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Olive                = new NamedColor("Olive",                new java.awt.Color(0xff808000, true));
	@Deprecated/**A color with an ARGB value of 0xff6b8e23<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(107,142,035,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor OliveDrab            = new NamedColor("OliveDrab",            new java.awt.Color(0xff6b8e23, true));
	@Deprecated/**A color with an ARGB value of 0xffffa500<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(255,165,000,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Orange               = new NamedColor("Orange",               new java.awt.Color(0xffffa500, true));
	@Deprecated/**A color with an ARGB value of 0xffff4500<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(255,069,000,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor OrangeRed            = new NamedColor("OrangeRed",            new java.awt.Color(0xffff4500, true));
	@Deprecated/**A color with an ARGB value of 0xffda70d6<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(218,112,214,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Orchid               = new NamedColor("Orchid",               new java.awt.Color(0xffda70d6, true));
	@Deprecated/**A color with an ARGB value of 0xffeee8aa<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(238,232,170,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor PaleGoldenRod        = new NamedColor("PaleGoldenRod",        new java.awt.Color(0xffeee8aa, true));
	@Deprecated/**A color with an ARGB value of 0xff98fb98<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(152,251,152,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor PaleGreen            = new NamedColor("PaleGreen",            new java.awt.Color(0xff98fb98, true));
	@Deprecated/**A color with an ARGB value of 0xffafeeee<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(175,238,238,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor PaleTurquoise        = new NamedColor("PaleTurquoise",        new java.awt.Color(0xffafeeee, true));
	@Deprecated/**A color with an ARGB value of 0xffdb7093<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(219,112,147,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor PaleVioletRed        = new NamedColor("PaleVioletRed",        new java.awt.Color(0xffdb7093, true));
	@Deprecated/**A color with an ARGB value of 0xffffefd5<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(255,239,213,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor PapayaWhip           = new NamedColor("PapayaWhip",           new java.awt.Color(0xffffefd5, true));
	@Deprecated/**A color with an ARGB value of 0xffffdab9<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(255,218,185,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor PeachPuff            = new NamedColor("PeachPuff",            new java.awt.Color(0xffffdab9, true));
	@Deprecated/**A color with an ARGB value of 0xffcd853f<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(205,133,063,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Peru                 = new NamedColor("Peru",                 new java.awt.Color(0xffcd853f, true));
	@Deprecated/**A color with an ARGB value of 0xffffc0cb<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(255,192,203,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Pink                 = new NamedColor("Pink",                 new java.awt.Color(0xffffc0cb, true));
	@Deprecated/**A color with an ARGB value of 0xffdda0dd<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(221,160,221,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Plum                 = new NamedColor("Plum",                 new java.awt.Color(0xffdda0dd, true));
	@Deprecated/**A color with an ARGB value of 0xffb0e0e6<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(176,224,230,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor PowderBlue           = new NamedColor("PowderBlue",           new java.awt.Color(0xffb0e0e6, true));
	@Deprecated/**A color with an ARGB value of 0xff800080<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(128,000,128,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Purple               = new NamedColor("Purple",               new java.awt.Color(0xff800080, true));
	@Deprecated/**A color with an ARGB value of 0xff663399<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(102,051,153,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor RebeccaPurple        = new NamedColor("RebeccaPurple",        new java.awt.Color(0xff663399, true));
	@Deprecated/**A color with an ARGB value of 0xffff0000<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(255,000,000,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Red                  = new NamedColor("Red",                  new java.awt.Color(0xffff0000, true));
	@Deprecated/**A color with an ARGB value of 0xffbc8f8f<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(188,143,143,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor RosyBrown            = new NamedColor("RosyBrown",            new java.awt.Color(0xffbc8f8f, true));
	@Deprecated/**A color with an ARGB value of 0xff4169e1<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(065,105,225,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor RoyalBlue            = new NamedColor("RoyalBlue",            new java.awt.Color(0xff4169e1, true));
	@Deprecated/**A color with an ARGB value of 0xff8b4513<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(139,069,019,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor SaddleBrown          = new NamedColor("SaddleBrown",          new java.awt.Color(0xff8b4513, true));
	@Deprecated/**A color with an ARGB value of 0xfffa8072<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(250,128,114,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Salmon               = new NamedColor("Salmon",               new java.awt.Color(0xfffa8072, true));
	@Deprecated/**A color with an ARGB value of 0xfff4a460<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(244,164,096,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor SandyBrown           = new NamedColor("SandyBrown",           new java.awt.Color(0xfff4a460, true));
	@Deprecated/**A color with an ARGB value of 0xff2e8b57<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(046,139,087,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor SeaGreen             = new NamedColor("SeaGreen",             new java.awt.Color(0xff2e8b57, true));
	@Deprecated/**A color with an ARGB value of 0xfffff5ee<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(255,245,238,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor SeaShell             = new NamedColor("SeaShell",             new java.awt.Color(0xfffff5ee, true));
	@Deprecated/**A color with an ARGB value of 0xffa0522d<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(160,082,045,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Sienna               = new NamedColor("Sienna",               new java.awt.Color(0xffa0522d, true));
	@Deprecated/**A color with an ARGB value of 0xffc0c0c0<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(192,192,192,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Silver               = new NamedColor("Silver",               new java.awt.Color(0xffc0c0c0, true));
	@Deprecated/**A color with an ARGB value of 0xff87ceeb<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(135,206,235,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor SkyBlue              = new NamedColor("SkyBlue",              new java.awt.Color(0xff87ceeb, true));
	@Deprecated/**A color with an ARGB value of 0xff6a5acd<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(106,090,205,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor SlateBlue            = new NamedColor("SlateBlue",            new java.awt.Color(0xff6a5acd, true));
	@Deprecated/**A color with an ARGB value of 0xff708090<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(112,128,144,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor SlateGray            = new NamedColor("SlateGray",            new java.awt.Color(0xff708090, true));
	@Deprecated/**A color with an ARGB value of 0xff708090<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(112,128,144,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor SlateGrey            = new NamedColor("SlateGrey",            new java.awt.Color(0xff708090, true));
	@Deprecated/**A color with an ARGB value of 0xfffffafa<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(255,250,250,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Snow                 = new NamedColor("Snow",                 new java.awt.Color(0xfffffafa, true));
	@Deprecated/**A color with an ARGB value of 0xff00ff7f<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(000,255,127,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor SpringGreen          = new NamedColor("SpringGreen",          new java.awt.Color(0xff00ff7f, true));
	@Deprecated/**A color with an ARGB value of 0xff4682b4<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(070,130,180,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor SteelBlue            = new NamedColor("SteelBlue",            new java.awt.Color(0xff4682b4, true));
	@Deprecated/**A color with an ARGB value of 0xffd2b48c<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(210,180,140,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Tan                  = new NamedColor("Tan",                  new java.awt.Color(0xffd2b48c, true));
	@Deprecated/**A color with an ARGB value of 0xff008080<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(000,128,128,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Teal                 = new NamedColor("Teal",                 new java.awt.Color(0xff008080, true));
	@Deprecated/**A color with an ARGB value of 0xffd8bfd8<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(216,191,216,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Thistle              = new NamedColor("Thistle",              new java.awt.Color(0xffd8bfd8, true));
	@Deprecated/**A color with an ARGB value of 0xffff6347<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(255,099,071,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Tomato               = new NamedColor("Tomato",               new java.awt.Color(0xffff6347, true));
	@Deprecated/**A color with an ARGB value of 0x00000000<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(000,000,000,0.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Transparent          = new NamedColor("Transparent",          new java.awt.Color(0x00000000, true));
	@Deprecated/**A color with an ARGB value of 0xff40e0d0<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(064,224,208,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Turquoise            = new NamedColor("Turquoise",            new java.awt.Color(0xff40e0d0, true));
	@Deprecated/**A color with an ARGB value of 0xffee82ee<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(238,130,238,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Violet               = new NamedColor("Violet",               new java.awt.Color(0xffee82ee, true));
	@Deprecated/**A color with an ARGB value of 0xfff5deb3<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(245,222,179,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Wheat                = new NamedColor("Wheat",                new java.awt.Color(0xfff5deb3, true));
	@Deprecated/**A color with an ARGB value of 0xffffffff<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(255,255,255,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor White                = new NamedColor("White",                new java.awt.Color(0xffffffff, true));
	@Deprecated/**A color with an ARGB value of 0xfff5f5f5<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(245,245,245,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor WhiteSmoke           = new NamedColor("WhiteSmoke",           new java.awt.Color(0xfff5f5f5, true));
	@Deprecated/**A color with an ARGB value of 0xffffff00<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(255,255,000,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor Yellow               = new NamedColor("Yellow",               new java.awt.Color(0xffffff00, true));
	@Deprecated/**A color with an ARGB value of 0xff9acd32<div style="border:1px solid black;width:40px;height:20px;background-color:rgba(154,205,050,1.0);float:right;margin: 0 10px 0 0"></div><br/><br/>*/
	public final static NamedColor YellowGreen          = new NamedColor("YellowGreen",          new java.awt.Color(0xff9acd32, true));
}
