package tools.locations;

/**
 * 3 letter ISO Country Codes
 */
public enum CountryCodes {
	AFG("Afghanistan"),
	ALB("Albania"),
	DZA("Algeria"),
	AND("Andorra"),
	AGO("Angola"),
	ATG("Antigua and Barbuda"),
	ARG("Argentina"),
	ARM("Armenia"),
	AUS("Australia"),
	AUT("Austria"),
	AZE("Azerbaijan"),
	BHS("Bahamas"),
	BHR("Bahrain"),
	BGD("Bangladesh"),
	BRB("Barbados"),
	BLR("Belarus"),
	BEL("Belgium"),
	BLZ("Belize"),
	BEN("Benin"),
	BTN("Bhutan"),
	BOL("Bolivia (Plurinational State of)"),
	BIH("Bosnia and Herzegovina"),
	BWA("Botswana"),
	BRA("Brazil"),
	BRN("Brunei Darussalam"),
	BGR("Bulgaria"),
	BFA("Burkina Faso"),
	BDI("Burundi"),
	CPV("Cabo Verde"),
	KHM("Cambodia"),
	CMR("Cameroon"),
	CAN("Canada"),
	CAF("Central African Republic"),
	TCD("Chad"),
	CHL("Chile"),
	CHN("China"),
	COL("Colombia"),
	COM("Comoros"),
	COG("Congo"),
	COK("Cook Islands"),
	CRI("Costa Rica"),
	CIV("Cote d'Ivoire"),
	HRV("Croatia"),
	CUB("Cuba"),
	CYP("Cyprus"),
	CZE("Czech Republic"),
	PRK("Democratic People's Republic of Korea"),
	COD("Democratic Republic of the Congo"),
	DNK("Denmark"),
	DJI("Djibouti"),
	DOM("Dominican Republic"),
	ECU("Ecuador"),
	EGY("Egypt"),
	SLV("El Salvador"),
	GNQ("Equatorial Guinea"),
	ERI("Eritrea"),
	EST("Estonia"),
	ETH("Ethiopia"),
	FJI("Fiji"),
	FIN("Finland"),
	FRA("France"),
	GAB("Gabon"),
	GMB("Gambia"),
	GEO("Georgia"),
	DEU("Germany"),
	GHA("Ghana"),
	GRC("Greece"),
	GRD("Grenada"),
	GTM("Guatemala"),
	GIN("Guinea"),
	GNB("Guinea-Bissau"),
	GUY("Guyana"),
	HTI("Haiti"),
	HND("Honduras"),
	HUN("Hungary"),
	ISL("Iceland"),
	IND("India"),
	IDN("Indonesia"),
	IRN("Iran (Islamic Republic of)"),
	IRQ("Iraq"),
	IRL("Ireland"),
	ISR("Israel"),
	ITA("Italy"),
	JAM("Jamaica"),
	JPN("Japan"),
	JOR("Jordan"),
	KAZ("Kazakhstan"),
	KEN("Kenya"),
	KIR("Kiribati"),
	KWT("Kuwait"),
	KGZ("Kyrgyzstan"),
	LAO("Lao People's Democratic Republic"),
	LVA("Latvia"),
	LBN("Lebanon"),
	LSO("Lesotho"),
	LBR("Liberia"),
	LBY("Libya"),
	LTU("Lithuania"),
	LUX("Luxembourg"),
	MDG("Madagascar"),
	MWI("Malawi"),
	MYS("Malaysia"),
	MDV("Maldives"),
	MLI("Mali"),
	MLT("Malta"),
	MHL("Marshall Islands"),
	MRT("Mauritania"),
	MUS("Mauritius"),
	MEX("Mexico"),
	FSM("Micronesia (Federated States of)"),
	MCO("Monaco"),
	MNG("Mongolia"),
	MNE("Montenegro"),
	MAR("Morocco"),
	MOZ("Mozambique"),
	MMR("Myanmar"),
	NAM("Namibia"),
	NRU("Nauru"),
	NPL("Nepal"),
	NLD("Netherlands"),
	NZL("New Zealand"),
	NIC("Nicaragua"),
	NER("Niger"),
	NGA("Nigeria"),
	NOR("Norway"),
	OMN("Oman"),
	PAK("Pakistan"),
	PLW("Palau"),
	PAN("Panama"),
	PNG("Papua New Guinea"),
	PRY("Paraguay"),
	PER("Peru"),
	PHL("Philippines"),
	POL("Poland"),
	PRT("Portugal"),
	QAT("Qatar"),
	KOR("Republic of Korea"),
	MDA("Republic of Moldova"),
	ROU("Romania"),
	RUS("Russian Federation"),
	RWA("Rwanda"),
	KNA("Saint Kitts and Nevis"),
	LCA("Saint Lucia"),
	VCT("Saint Vincent and the Grenadines"),
	WSM("Samoa"),
	SMR("San Marino"),
	STP("Sao Tome and Principe"),
	SAU("Saudi Arabia"),
	SEN("Senegal"),
	SRB("Serbia"),
	SYC("Seychelles"),
	SLE("Sierra Leone"),
	SGP("Singapore"),
	SVK("Slovakia"),
	SVN("Slovenia"),
	SLB("Solomon Islands"),
	SOM("Somalia"),
	ZAF("South Africa"),
	SSD("South Sudan"),
	ESP("Spain"),
	LKA("Sri Lanka"),
	SDN("Sudan"),
	SUR("Suriname"),
	SWZ("Swaziland"),
	SWE("Sweden"),
	CHE("Switzerland"),
	SYR("Syrian Arab Republic"),
	TJK("Tajikistan"),
	THA("Thailand"),
	MKD("The former Yugoslav Republic of Macedonia"),
	TLS("Timor-Leste"),
	TGO("Togo"),
	TON("Tonga"),
	TTO("Trinidad and Tobago"),
	TUN("Tunisia"),
	TUR("Turkey"),
	TKM("Turkmenistan"),
	UGA("Uganda"),
	UKR("Ukraine"),
	ARE("United Arab Emirates"),
	GBR("United Kingdom of Great Britain and Northern Ireland"),
	TZA("United Republic of Tanzania"),
	USA("United States of America"),
	URY("Uruguay"),
	UZB("Uzbekistan"),
	VUT("Vanuatu"),
	VEN("Venezuela (Bolivarian Republic of)"),
	VNM("Viet Nam"),
	YEM("Yemen"),
	ZMB("Zambia"),
	ZWE("Zimbabwe");
	
	private final String cnme;
	private CountryCodes(String name)
	{
		cnme=name;
	}
	public String getCountryName()
	{
		return cnme;
	}
}
